// AUTO-GENERATED by scripts/export_data.py — do not edit manually

import type { Variant } from './predictions';

export interface TeamProb {
  pR32: number; pS16: number; pE8: number;
  pSemis: number; pFinal: number; pChampion: number;
}

export interface VariantProbs { nSims: number; teams: Record<string, TeamProb>; }

export const probabilities: Record<Variant, VariantProbs> = {
  "misterclaude": {
    "nSims": 500,
    "teams": {
      "Spain": {
        "pR32": 0.962,
        "pS16": 0.628,
        "pE8": 0.358,
        "pSemis": 0.246,
        "pFinal": 0.16,
        "pChampion": 0.1
      },
      "England": {
        "pR32": 0.912,
        "pS16": 0.546,
        "pE8": 0.358,
        "pSemis": 0.222,
        "pFinal": 0.146,
        "pChampion": 0.09
      },
      "France": {
        "pR32": 0.866,
        "pS16": 0.538,
        "pE8": 0.35,
        "pSemis": 0.22,
        "pFinal": 0.142,
        "pChampion": 0.082
      },
      "Netherlands": {
        "pR32": 0.898,
        "pS16": 0.536,
        "pE8": 0.364,
        "pSemis": 0.212,
        "pFinal": 0.122,
        "pChampion": 0.074
      },
      "Colombia": {
        "pR32": 0.864,
        "pS16": 0.52,
        "pE8": 0.338,
        "pSemis": 0.202,
        "pFinal": 0.114,
        "pChampion": 0.068
      },
      "Portugal": {
        "pR32": 0.842,
        "pS16": 0.5,
        "pE8": 0.308,
        "pSemis": 0.21,
        "pFinal": 0.126,
        "pChampion": 0.066
      },
      "Argentina": {
        "pR32": 0.88,
        "pS16": 0.57,
        "pE8": 0.352,
        "pSemis": 0.224,
        "pFinal": 0.12,
        "pChampion": 0.062
      },
      "Brazil": {
        "pR32": 0.924,
        "pS16": 0.57,
        "pE8": 0.358,
        "pSemis": 0.192,
        "pFinal": 0.096,
        "pChampion": 0.048
      },
      "Germany": {
        "pR32": 0.96,
        "pS16": 0.586,
        "pE8": 0.326,
        "pSemis": 0.184,
        "pFinal": 0.09,
        "pChampion": 0.046
      },
      "Turkey": {
        "pR32": 0.818,
        "pS16": 0.512,
        "pE8": 0.288,
        "pSemis": 0.12,
        "pFinal": 0.074,
        "pChampion": 0.036
      },
      "Ecuador": {
        "pR32": 0.916,
        "pS16": 0.504,
        "pE8": 0.264,
        "pSemis": 0.142,
        "pFinal": 0.062,
        "pChampion": 0.034
      },
      "Norway": {
        "pR32": 0.796,
        "pS16": 0.41,
        "pE8": 0.226,
        "pSemis": 0.114,
        "pFinal": 0.06,
        "pChampion": 0.03
      },
      "Croatia": {
        "pR32": 0.868,
        "pS16": 0.502,
        "pE8": 0.276,
        "pSemis": 0.156,
        "pFinal": 0.076,
        "pChampion": 0.03
      },
      "Morocco": {
        "pR32": 0.816,
        "pS16": 0.436,
        "pE8": 0.244,
        "pSemis": 0.136,
        "pFinal": 0.056,
        "pChampion": 0.026
      },
      "Belgium": {
        "pR32": 0.878,
        "pS16": 0.548,
        "pE8": 0.274,
        "pSemis": 0.1,
        "pFinal": 0.05,
        "pChampion": 0.024
      },
      "Japan": {
        "pR32": 0.834,
        "pS16": 0.422,
        "pE8": 0.228,
        "pSemis": 0.112,
        "pFinal": 0.048,
        "pChampion": 0.022
      },
      "Switzerland": {
        "pR32": 0.93,
        "pS16": 0.51,
        "pE8": 0.228,
        "pSemis": 0.104,
        "pFinal": 0.038,
        "pChampion": 0.018
      },
      "Senegal": {
        "pR32": 0.758,
        "pS16": 0.388,
        "pE8": 0.19,
        "pSemis": 0.098,
        "pFinal": 0.034,
        "pChampion": 0.018
      },
      "Austria": {
        "pR32": 0.726,
        "pS16": 0.35,
        "pE8": 0.178,
        "pSemis": 0.096,
        "pFinal": 0.034,
        "pChampion": 0.016
      },
      "Canada": {
        "pR32": 0.94,
        "pS16": 0.494,
        "pE8": 0.188,
        "pSemis": 0.09,
        "pFinal": 0.038,
        "pChampion": 0.014
      },
      "Mexico": {
        "pR32": 0.904,
        "pS16": 0.496,
        "pE8": 0.226,
        "pSemis": 0.076,
        "pFinal": 0.04,
        "pChampion": 0.01
      },
      "Uruguay": {
        "pR32": 0.814,
        "pS16": 0.376,
        "pE8": 0.18,
        "pSemis": 0.086,
        "pFinal": 0.034,
        "pChampion": 0.01
      },
      "Algeria": {
        "pR32": 0.654,
        "pS16": 0.33,
        "pE8": 0.138,
        "pSemis": 0.05,
        "pFinal": 0.024,
        "pChampion": 0.01
      },
      "Panama": {
        "pR32": 0.664,
        "pS16": 0.264,
        "pE8": 0.122,
        "pSemis": 0.068,
        "pFinal": 0.024,
        "pChampion": 0.01
      },
      "United States": {
        "pR32": 0.652,
        "pS16": 0.312,
        "pE8": 0.116,
        "pSemis": 0.032,
        "pFinal": 0.014,
        "pChampion": 0.008
      },
      "Egypt": {
        "pR32": 0.626,
        "pS16": 0.274,
        "pE8": 0.096,
        "pSemis": 0.032,
        "pFinal": 0.016,
        "pChampion": 0.008
      },
      "South Korea": {
        "pR32": 0.766,
        "pS16": 0.354,
        "pE8": 0.126,
        "pSemis": 0.044,
        "pFinal": 0.018,
        "pChampion": 0.004
      },
      "Paraguay": {
        "pR32": 0.614,
        "pS16": 0.29,
        "pE8": 0.13,
        "pSemis": 0.048,
        "pFinal": 0.012,
        "pChampion": 0.004
      },
      "Australia": {
        "pR32": 0.632,
        "pS16": 0.31,
        "pE8": 0.154,
        "pSemis": 0.056,
        "pFinal": 0.022,
        "pChampion": 0.004
      },
      "Tunisia": {
        "pR32": 0.368,
        "pS16": 0.1,
        "pE8": 0.03,
        "pSemis": 0.016,
        "pFinal": 0.008,
        "pChampion": 0.004
      },
      "Iran": {
        "pR32": 0.758,
        "pS16": 0.408,
        "pE8": 0.184,
        "pSemis": 0.06,
        "pFinal": 0.016,
        "pChampion": 0.004
      },
      "Jordan": {
        "pR32": 0.412,
        "pS16": 0.146,
        "pE8": 0.034,
        "pSemis": 0.024,
        "pFinal": 0.016,
        "pChampion": 0.004
      },
      "Uzbekistan": {
        "pR32": 0.554,
        "pS16": 0.216,
        "pE8": 0.098,
        "pSemis": 0.036,
        "pFinal": 0.014,
        "pChampion": 0.004
      },
      "Czech Republic": {
        "pR32": 0.648,
        "pS16": 0.298,
        "pE8": 0.134,
        "pSemis": 0.034,
        "pFinal": 0.008,
        "pChampion": 0.002
      },
      "Haiti": {
        "pR32": 0.238,
        "pS16": 0.04,
        "pE8": 0.012,
        "pSemis": 0.004,
        "pFinal": 0.002,
        "pChampion": 0.002
      },
      "Scotland": {
        "pR32": 0.684,
        "pS16": 0.256,
        "pE8": 0.098,
        "pSemis": 0.024,
        "pFinal": 0.006,
        "pChampion": 0.002
      },
      "Ivory Coast": {
        "pR32": 0.752,
        "pS16": 0.328,
        "pE8": 0.112,
        "pSemis": 0.042,
        "pFinal": 0.022,
        "pChampion": 0.002
      },
      "Sweden": {
        "pR32": 0.582,
        "pS16": 0.204,
        "pE8": 0.068,
        "pSemis": 0.03,
        "pFinal": 0.006,
        "pChampion": 0.002
      },
      "New Zealand": {
        "pR32": 0.396,
        "pS16": 0.106,
        "pE8": 0.032,
        "pSemis": 0.006,
        "pFinal": 0.004,
        "pChampion": 0.002
      },
      "South Africa": {
        "pR32": 0.356,
        "pS16": 0.128,
        "pE8": 0.028,
        "pSemis": 0.008,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "Bosnia and Herzegovina": {
        "pR32": 0.528,
        "pS16": 0.178,
        "pE8": 0.044,
        "pSemis": 0.014,
        "pFinal": 0.002,
        "pChampion": 0.0
      },
      "Qatar": {
        "pR32": 0.228,
        "pS16": 0.038,
        "pE8": 0.008,
        "pSemis": 0.0,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "Curaçao": {
        "pR32": 0.076,
        "pS16": 0.004,
        "pE8": 0.0,
        "pSemis": 0.0,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "Cape Verde": {
        "pR32": 0.484,
        "pS16": 0.132,
        "pE8": 0.04,
        "pSemis": 0.01,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "Saudi Arabia": {
        "pR32": 0.34,
        "pS16": 0.094,
        "pE8": 0.026,
        "pSemis": 0.004,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "Iraq": {
        "pR32": 0.252,
        "pS16": 0.062,
        "pE8": 0.014,
        "pSemis": 0.0,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "DR Congo": {
        "pR32": 0.404,
        "pS16": 0.132,
        "pE8": 0.042,
        "pSemis": 0.016,
        "pFinal": 0.006,
        "pChampion": 0.0
      },
      "Ghana": {
        "pR32": 0.226,
        "pS16": 0.054,
        "pE8": 0.012,
        "pSemis": 0.0,
        "pFinal": 0.0,
        "pChampion": 0.0
      }
    }
  },
  "gemaldini": {
    "nSims": 500,
    "teams": {
      "England": {
        "pR32": 0.936,
        "pS16": 0.618,
        "pE8": 0.438,
        "pSemis": 0.284,
        "pFinal": 0.162,
        "pChampion": 0.102
      },
      "Argentina": {
        "pR32": 0.884,
        "pS16": 0.556,
        "pE8": 0.374,
        "pSemis": 0.246,
        "pFinal": 0.146,
        "pChampion": 0.076
      },
      "Netherlands": {
        "pR32": 0.882,
        "pS16": 0.524,
        "pE8": 0.304,
        "pSemis": 0.194,
        "pFinal": 0.112,
        "pChampion": 0.074
      },
      "Spain": {
        "pR32": 0.968,
        "pS16": 0.562,
        "pE8": 0.332,
        "pSemis": 0.2,
        "pFinal": 0.124,
        "pChampion": 0.072
      },
      "France": {
        "pR32": 0.88,
        "pS16": 0.544,
        "pE8": 0.31,
        "pSemis": 0.186,
        "pFinal": 0.11,
        "pChampion": 0.066
      },
      "Portugal": {
        "pR32": 0.894,
        "pS16": 0.516,
        "pE8": 0.304,
        "pSemis": 0.194,
        "pFinal": 0.116,
        "pChampion": 0.066
      },
      "Norway": {
        "pR32": 0.892,
        "pS16": 0.604,
        "pE8": 0.366,
        "pSemis": 0.216,
        "pFinal": 0.106,
        "pChampion": 0.062
      },
      "Belgium": {
        "pR32": 0.912,
        "pS16": 0.618,
        "pE8": 0.362,
        "pSemis": 0.168,
        "pFinal": 0.102,
        "pChampion": 0.054
      },
      "Croatia": {
        "pR32": 0.904,
        "pS16": 0.51,
        "pE8": 0.304,
        "pSemis": 0.158,
        "pFinal": 0.076,
        "pChampion": 0.044
      },
      "Germany": {
        "pR32": 0.954,
        "pS16": 0.588,
        "pE8": 0.336,
        "pSemis": 0.164,
        "pFinal": 0.076,
        "pChampion": 0.042
      },
      "Colombia": {
        "pR32": 0.856,
        "pS16": 0.508,
        "pE8": 0.292,
        "pSemis": 0.16,
        "pFinal": 0.082,
        "pChampion": 0.04
      },
      "Switzerland": {
        "pR32": 0.954,
        "pS16": 0.618,
        "pE8": 0.334,
        "pSemis": 0.178,
        "pFinal": 0.092,
        "pChampion": 0.036
      },
      "Brazil": {
        "pR32": 0.912,
        "pS16": 0.538,
        "pE8": 0.296,
        "pSemis": 0.162,
        "pFinal": 0.096,
        "pChampion": 0.036
      },
      "Austria": {
        "pR32": 0.848,
        "pS16": 0.494,
        "pE8": 0.292,
        "pSemis": 0.152,
        "pFinal": 0.068,
        "pChampion": 0.034
      },
      "Turkey": {
        "pR32": 0.842,
        "pS16": 0.546,
        "pE8": 0.288,
        "pSemis": 0.156,
        "pFinal": 0.078,
        "pChampion": 0.032
      },
      "Uruguay": {
        "pR32": 0.832,
        "pS16": 0.362,
        "pE8": 0.18,
        "pSemis": 0.08,
        "pFinal": 0.046,
        "pChampion": 0.024
      },
      "Ecuador": {
        "pR32": 0.936,
        "pS16": 0.486,
        "pE8": 0.228,
        "pSemis": 0.13,
        "pFinal": 0.062,
        "pChampion": 0.02
      },
      "Mexico": {
        "pR32": 0.902,
        "pS16": 0.478,
        "pE8": 0.184,
        "pSemis": 0.076,
        "pFinal": 0.036,
        "pChampion": 0.018
      },
      "Japan": {
        "pR32": 0.806,
        "pS16": 0.358,
        "pE8": 0.192,
        "pSemis": 0.098,
        "pFinal": 0.036,
        "pChampion": 0.016
      },
      "Senegal": {
        "pR32": 0.664,
        "pS16": 0.308,
        "pE8": 0.134,
        "pSemis": 0.054,
        "pFinal": 0.026,
        "pChampion": 0.014
      },
      "Czech Republic": {
        "pR32": 0.79,
        "pS16": 0.356,
        "pE8": 0.134,
        "pSemis": 0.056,
        "pFinal": 0.024,
        "pChampion": 0.008
      },
      "Canada": {
        "pR32": 0.88,
        "pS16": 0.448,
        "pE8": 0.18,
        "pSemis": 0.06,
        "pFinal": 0.022,
        "pChampion": 0.008
      },
      "Morocco": {
        "pR32": 0.82,
        "pS16": 0.418,
        "pE8": 0.214,
        "pSemis": 0.082,
        "pFinal": 0.028,
        "pChampion": 0.008
      },
      "Panama": {
        "pR32": 0.632,
        "pS16": 0.248,
        "pE8": 0.084,
        "pSemis": 0.04,
        "pFinal": 0.016,
        "pChampion": 0.008
      },
      "South Korea": {
        "pR32": 0.726,
        "pS16": 0.296,
        "pE8": 0.11,
        "pSemis": 0.028,
        "pFinal": 0.012,
        "pChampion": 0.006
      },
      "Scotland": {
        "pR32": 0.762,
        "pS16": 0.31,
        "pE8": 0.14,
        "pSemis": 0.056,
        "pFinal": 0.012,
        "pChampion": 0.006
      },
      "Paraguay": {
        "pR32": 0.588,
        "pS16": 0.266,
        "pE8": 0.098,
        "pSemis": 0.036,
        "pFinal": 0.012,
        "pChampion": 0.004
      },
      "Australia": {
        "pR32": 0.626,
        "pS16": 0.286,
        "pE8": 0.108,
        "pSemis": 0.04,
        "pFinal": 0.012,
        "pChampion": 0.004
      },
      "Ivory Coast": {
        "pR32": 0.792,
        "pS16": 0.316,
        "pE8": 0.106,
        "pSemis": 0.028,
        "pFinal": 0.012,
        "pChampion": 0.004
      },
      "Sweden": {
        "pR32": 0.66,
        "pS16": 0.254,
        "pE8": 0.118,
        "pSemis": 0.048,
        "pFinal": 0.018,
        "pChampion": 0.004
      },
      "South Africa": {
        "pR32": 0.292,
        "pS16": 0.08,
        "pE8": 0.026,
        "pSemis": 0.004,
        "pFinal": 0.002,
        "pChampion": 0.002
      },
      "United States": {
        "pR32": 0.646,
        "pS16": 0.242,
        "pE8": 0.076,
        "pSemis": 0.022,
        "pFinal": 0.014,
        "pChampion": 0.002
      },
      "Iran": {
        "pR32": 0.754,
        "pS16": 0.364,
        "pE8": 0.164,
        "pSemis": 0.046,
        "pFinal": 0.012,
        "pChampion": 0.002
      },
      "Algeria": {
        "pR32": 0.606,
        "pS16": 0.288,
        "pE8": 0.116,
        "pSemis": 0.046,
        "pFinal": 0.014,
        "pChampion": 0.002
      },
      "DR Congo": {
        "pR32": 0.388,
        "pS16": 0.134,
        "pE8": 0.05,
        "pSemis": 0.02,
        "pFinal": 0.008,
        "pChampion": 0.002
      },
      "Uzbekistan": {
        "pR32": 0.48,
        "pS16": 0.154,
        "pE8": 0.048,
        "pSemis": 0.018,
        "pFinal": 0.006,
        "pChampion": 0.002
      },
      "Bosnia and Herzegovina": {
        "pR32": 0.66,
        "pS16": 0.286,
        "pE8": 0.11,
        "pSemis": 0.036,
        "pFinal": 0.014,
        "pChampion": 0.0
      },
      "Qatar": {
        "pR32": 0.168,
        "pS16": 0.026,
        "pE8": 0.002,
        "pSemis": 0.0,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "Haiti": {
        "pR32": 0.224,
        "pS16": 0.04,
        "pE8": 0.012,
        "pSemis": 0.006,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "Curaçao": {
        "pR32": 0.064,
        "pS16": 0.004,
        "pE8": 0.002,
        "pSemis": 0.0,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "Tunisia": {
        "pR32": 0.308,
        "pS16": 0.076,
        "pE8": 0.02,
        "pSemis": 0.002,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "Egypt": {
        "pR32": 0.642,
        "pS16": 0.296,
        "pE8": 0.1,
        "pSemis": 0.03,
        "pFinal": 0.008,
        "pChampion": 0.0
      },
      "New Zealand": {
        "pR32": 0.31,
        "pS16": 0.098,
        "pE8": 0.032,
        "pSemis": 0.01,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "Cape Verde": {
        "pR32": 0.444,
        "pS16": 0.11,
        "pE8": 0.032,
        "pSemis": 0.01,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "Saudi Arabia": {
        "pR32": 0.344,
        "pS16": 0.086,
        "pE8": 0.02,
        "pSemis": 0.002,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "Iraq": {
        "pR32": 0.218,
        "pS16": 0.048,
        "pE8": 0.012,
        "pSemis": 0.002,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "Jordan": {
        "pR32": 0.324,
        "pS16": 0.1,
        "pE8": 0.032,
        "pSemis": 0.016,
        "pFinal": 0.002,
        "pChampion": 0.0
      },
      "Ghana": {
        "pR32": 0.194,
        "pS16": 0.034,
        "pE8": 0.004,
        "pSemis": 0.0,
        "pFinal": 0.0,
        "pChampion": 0.0
      }
    }
  },
  "dav_gpo": {
    "nSims": 500,
    "teams": {
      "Argentina": {
        "pR32": 0.936,
        "pS16": 0.634,
        "pE8": 0.45,
        "pSemis": 0.298,
        "pFinal": 0.18,
        "pChampion": 0.104
      },
      "England": {
        "pR32": 0.892,
        "pS16": 0.552,
        "pE8": 0.324,
        "pSemis": 0.22,
        "pFinal": 0.15,
        "pChampion": 0.102
      },
      "France": {
        "pR32": 0.906,
        "pS16": 0.612,
        "pE8": 0.35,
        "pSemis": 0.204,
        "pFinal": 0.124,
        "pChampion": 0.07
      },
      "Colombia": {
        "pR32": 0.908,
        "pS16": 0.554,
        "pE8": 0.364,
        "pSemis": 0.222,
        "pFinal": 0.136,
        "pChampion": 0.07
      },
      "Spain": {
        "pR32": 0.958,
        "pS16": 0.576,
        "pE8": 0.364,
        "pSemis": 0.222,
        "pFinal": 0.13,
        "pChampion": 0.066
      },
      "Ecuador": {
        "pR32": 0.962,
        "pS16": 0.606,
        "pE8": 0.372,
        "pSemis": 0.2,
        "pFinal": 0.116,
        "pChampion": 0.064
      },
      "Brazil": {
        "pR32": 0.942,
        "pS16": 0.56,
        "pE8": 0.328,
        "pSemis": 0.204,
        "pFinal": 0.102,
        "pChampion": 0.058
      },
      "Mexico": {
        "pR32": 0.966,
        "pS16": 0.668,
        "pE8": 0.394,
        "pSemis": 0.214,
        "pFinal": 0.108,
        "pChampion": 0.054
      },
      "Netherlands": {
        "pR32": 0.906,
        "pS16": 0.504,
        "pE8": 0.294,
        "pSemis": 0.178,
        "pFinal": 0.094,
        "pChampion": 0.05
      },
      "Portugal": {
        "pR32": 0.856,
        "pS16": 0.47,
        "pE8": 0.27,
        "pSemis": 0.136,
        "pFinal": 0.066,
        "pChampion": 0.038
      },
      "Paraguay": {
        "pR32": 0.78,
        "pS16": 0.506,
        "pE8": 0.29,
        "pSemis": 0.142,
        "pFinal": 0.066,
        "pChampion": 0.036
      },
      "Germany": {
        "pR32": 0.952,
        "pS16": 0.546,
        "pE8": 0.288,
        "pSemis": 0.146,
        "pFinal": 0.082,
        "pChampion": 0.034
      },
      "Croatia": {
        "pR32": 0.848,
        "pS16": 0.47,
        "pE8": 0.222,
        "pSemis": 0.124,
        "pFinal": 0.058,
        "pChampion": 0.034
      },
      "Turkey": {
        "pR32": 0.782,
        "pS16": 0.456,
        "pE8": 0.222,
        "pSemis": 0.106,
        "pFinal": 0.048,
        "pChampion": 0.032
      },
      "Belgium": {
        "pR32": 0.856,
        "pS16": 0.524,
        "pE8": 0.246,
        "pSemis": 0.116,
        "pFinal": 0.048,
        "pChampion": 0.022
      },
      "Uruguay": {
        "pR32": 0.872,
        "pS16": 0.428,
        "pE8": 0.234,
        "pSemis": 0.124,
        "pFinal": 0.062,
        "pChampion": 0.02
      },
      "Norway": {
        "pR32": 0.764,
        "pS16": 0.392,
        "pE8": 0.176,
        "pSemis": 0.088,
        "pFinal": 0.034,
        "pChampion": 0.02
      },
      "Morocco": {
        "pR32": 0.822,
        "pS16": 0.38,
        "pE8": 0.188,
        "pSemis": 0.09,
        "pFinal": 0.036,
        "pChampion": 0.016
      },
      "Japan": {
        "pR32": 0.846,
        "pS16": 0.47,
        "pE8": 0.252,
        "pSemis": 0.126,
        "pFinal": 0.05,
        "pChampion": 0.016
      },
      "Austria": {
        "pR32": 0.704,
        "pS16": 0.32,
        "pE8": 0.146,
        "pSemis": 0.06,
        "pFinal": 0.024,
        "pChampion": 0.014
      },
      "Switzerland": {
        "pR32": 0.93,
        "pS16": 0.522,
        "pE8": 0.234,
        "pSemis": 0.084,
        "pFinal": 0.034,
        "pChampion": 0.012
      },
      "Senegal": {
        "pR32": 0.708,
        "pS16": 0.328,
        "pE8": 0.118,
        "pSemis": 0.054,
        "pFinal": 0.03,
        "pChampion": 0.012
      },
      "Canada": {
        "pR32": 0.936,
        "pS16": 0.464,
        "pE8": 0.196,
        "pSemis": 0.062,
        "pFinal": 0.026,
        "pChampion": 0.01
      },
      "Panama": {
        "pR32": 0.764,
        "pS16": 0.358,
        "pE8": 0.174,
        "pSemis": 0.07,
        "pFinal": 0.034,
        "pChampion": 0.01
      },
      "Iran": {
        "pR32": 0.82,
        "pS16": 0.396,
        "pE8": 0.188,
        "pSemis": 0.08,
        "pFinal": 0.028,
        "pChampion": 0.008
      },
      "Australia": {
        "pR32": 0.54,
        "pS16": 0.256,
        "pE8": 0.124,
        "pSemis": 0.034,
        "pFinal": 0.016,
        "pChampion": 0.006
      },
      "South Korea": {
        "pR32": 0.72,
        "pS16": 0.326,
        "pE8": 0.128,
        "pSemis": 0.05,
        "pFinal": 0.022,
        "pChampion": 0.004
      },
      "Scotland": {
        "pR32": 0.656,
        "pS16": 0.232,
        "pE8": 0.088,
        "pSemis": 0.042,
        "pFinal": 0.016,
        "pChampion": 0.004
      },
      "Ivory Coast": {
        "pR32": 0.788,
        "pS16": 0.292,
        "pE8": 0.13,
        "pSemis": 0.04,
        "pFinal": 0.008,
        "pChampion": 0.004
      },
      "Algeria": {
        "pR32": 0.648,
        "pS16": 0.288,
        "pE8": 0.11,
        "pSemis": 0.04,
        "pFinal": 0.016,
        "pChampion": 0.004
      },
      "United States": {
        "pR32": 0.624,
        "pS16": 0.276,
        "pE8": 0.094,
        "pSemis": 0.032,
        "pFinal": 0.01,
        "pChampion": 0.002
      },
      "Sweden": {
        "pR32": 0.574,
        "pS16": 0.214,
        "pE8": 0.074,
        "pSemis": 0.03,
        "pFinal": 0.008,
        "pChampion": 0.002
      },
      "Egypt": {
        "pR32": 0.656,
        "pS16": 0.28,
        "pE8": 0.102,
        "pSemis": 0.03,
        "pFinal": 0.014,
        "pChampion": 0.002
      },
      "South Africa": {
        "pR32": 0.336,
        "pS16": 0.09,
        "pE8": 0.024,
        "pSemis": 0.008,
        "pFinal": 0.002,
        "pChampion": 0.0
      },
      "Czech Republic": {
        "pR32": 0.616,
        "pS16": 0.238,
        "pE8": 0.098,
        "pSemis": 0.028,
        "pFinal": 0.002,
        "pChampion": 0.0
      },
      "Bosnia and Herzegovina": {
        "pR32": 0.59,
        "pS16": 0.21,
        "pE8": 0.062,
        "pSemis": 0.018,
        "pFinal": 0.002,
        "pChampion": 0.0
      },
      "Qatar": {
        "pR32": 0.178,
        "pS16": 0.038,
        "pE8": 0.002,
        "pSemis": 0.0,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "Haiti": {
        "pR32": 0.218,
        "pS16": 0.044,
        "pE8": 0.014,
        "pSemis": 0.0,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "Curaçao": {
        "pR32": 0.048,
        "pS16": 0.004,
        "pE8": 0.0,
        "pSemis": 0.0,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "Tunisia": {
        "pR32": 0.34,
        "pS16": 0.084,
        "pE8": 0.018,
        "pSemis": 0.006,
        "pFinal": 0.004,
        "pChampion": 0.0
      },
      "New Zealand": {
        "pR32": 0.362,
        "pS16": 0.098,
        "pE8": 0.03,
        "pSemis": 0.006,
        "pFinal": 0.002,
        "pChampion": 0.0
      },
      "Cape Verde": {
        "pR32": 0.46,
        "pS16": 0.12,
        "pE8": 0.048,
        "pSemis": 0.01,
        "pFinal": 0.002,
        "pChampion": 0.0
      },
      "Saudi Arabia": {
        "pR32": 0.304,
        "pS16": 0.064,
        "pE8": 0.018,
        "pSemis": 0.006,
        "pFinal": 0.002,
        "pChampion": 0.0
      },
      "Iraq": {
        "pR32": 0.314,
        "pS16": 0.094,
        "pE8": 0.03,
        "pSemis": 0.014,
        "pFinal": 0.004,
        "pChampion": 0.0
      },
      "Jordan": {
        "pR32": 0.382,
        "pS16": 0.108,
        "pE8": 0.03,
        "pSemis": 0.012,
        "pFinal": 0.002,
        "pChampion": 0.0
      },
      "DR Congo": {
        "pR32": 0.4,
        "pS16": 0.128,
        "pE8": 0.034,
        "pSemis": 0.012,
        "pFinal": 0.0,
        "pChampion": 0.0
      },
      "Uzbekistan": {
        "pR32": 0.474,
        "pS16": 0.17,
        "pE8": 0.052,
        "pSemis": 0.012,
        "pFinal": 0.002,
        "pChampion": 0.0
      },
      "Ghana": {
        "pR32": 0.156,
        "pS16": 0.05,
        "pE8": 0.006,
        "pSemis": 0.0,
        "pFinal": 0.0,
        "pChampion": 0.0
      }
    }
  }
};
