// AUTO-GENERATED by scripts/export_data.py — do not edit manually

import type { Variant, TournamentRounds } from './predictions';

// Bracket OFICIAL de eliminatorias (clasificados y cruces reales) con los
// resultados PREDICHOS por el modelo. grupos = [] (solo se muestran eliminatorias).
export const realBracketReady: boolean = true;

export const realBracket: Partial<Record<Variant, TournamentRounds>> = {
  "misterclaude": {
    "grupos": [],
    "r32": [
      {
        "team1": "South Africa",
        "score1": 0,
        "score2": 1,
        "team2": "Canada"
      },
      {
        "team1": "Brazil",
        "score1": 2,
        "score2": 1,
        "team2": "Japan"
      },
      {
        "team1": "Germany",
        "score1": 2,
        "score2": 1,
        "team2": "Paraguay"
      },
      {
        "team1": "Netherlands",
        "score1": 1,
        "score2": 2,
        "team2": "Morocco"
      },
      {
        "team1": "Ivory Coast",
        "score1": 2,
        "score2": 1,
        "team2": "Norway"
      },
      {
        "team1": "France",
        "score1": 2,
        "score2": 1,
        "team2": "Sweden"
      },
      {
        "team1": "Mexico",
        "score1": 1,
        "score2": 2,
        "team2": "Ecuador"
      },
      {
        "team1": "England",
        "score1": 1,
        "score2": 0,
        "team2": "DR Congo"
      },
      {
        "team1": "Belgium",
        "score1": 2,
        "score2": 1,
        "team2": "Senegal"
      },
      {
        "team1": "United States",
        "score1": 2,
        "score2": 1,
        "team2": "Bosnia and Herzegovina"
      },
      {
        "team1": "Spain",
        "score1": 2,
        "score2": 1,
        "team2": "Austria"
      },
      {
        "team1": "Portugal",
        "score1": 2,
        "score2": 3,
        "team2": "Croatia"
      },
      {
        "team1": "Switzerland",
        "score1": 3,
        "score2": 2,
        "team2": "Algeria"
      },
      {
        "team1": "Australia",
        "score1": 2,
        "score2": 1,
        "team2": "Egypt"
      },
      {
        "team1": "Argentina",
        "score1": 2,
        "score2": 1,
        "team2": "Cape Verde"
      },
      {
        "team1": "Colombia",
        "score1": 4,
        "score2": 1,
        "team2": "Ghana"
      }
    ],
    "sweet16": [
      {
        "team1": "Canada",
        "score1": 2,
        "score2": 1,
        "team2": "Morocco"
      },
      {
        "team1": "Germany",
        "score1": 2,
        "score2": 1,
        "team2": "France"
      },
      {
        "team1": "Brazil",
        "score1": 2,
        "score2": 1,
        "team2": "Ivory Coast"
      },
      {
        "team1": "Ecuador",
        "score1": 0,
        "score2": 1,
        "team2": "England"
      },
      {
        "team1": "Spain",
        "score1": 1,
        "score2": 0,
        "team2": "Croatia"
      },
      {
        "team1": "United States",
        "score1": 3,
        "score2": 2,
        "team2": "Belgium"
      },
      {
        "team1": "Argentina",
        "score1": 2,
        "score2": 1,
        "team2": "Australia"
      },
      {
        "team1": "Switzerland",
        "score1": 2,
        "score2": 3,
        "team2": "Colombia"
      }
    ],
    "elite8": [
      {
        "team1": "Canada",
        "score1": 2,
        "score2": 3,
        "team2": "Germany"
      },
      {
        "team1": "Spain",
        "score1": 3,
        "score2": 2,
        "team2": "United States"
      },
      {
        "team1": "Brazil",
        "score1": 3,
        "score2": 2,
        "team2": "England"
      },
      {
        "team1": "Argentina",
        "score1": 1,
        "score2": 0,
        "team2": "Colombia"
      }
    ],
    "semis": [
      {
        "team1": "Germany",
        "score1": 0,
        "score2": 2,
        "team2": "Spain"
      },
      {
        "team1": "Brazil",
        "score1": 1,
        "score2": 2,
        "team2": "Argentina"
      }
    ],
    "third": [
      {
        "team1": "Germany",
        "score1": 1,
        "score2": 2,
        "team2": "Brazil"
      }
    ],
    "final": [
      {
        "team1": "Spain",
        "score1": 1,
        "score2": 2,
        "team2": "Argentina"
      }
    ]
  },
  "gemaldini": {
    "grupos": [],
    "r32": [
      {
        "team1": "South Africa",
        "score1": 0,
        "score2": 1,
        "team2": "Canada"
      },
      {
        "team1": "Brazil",
        "score1": 2,
        "score2": 1,
        "team2": "Japan"
      },
      {
        "team1": "Germany",
        "score1": 2,
        "score2": 1,
        "team2": "Paraguay"
      },
      {
        "team1": "Netherlands",
        "score1": 1,
        "score2": 2,
        "team2": "Morocco"
      },
      {
        "team1": "Ivory Coast",
        "score1": 2,
        "score2": 1,
        "team2": "Norway"
      },
      {
        "team1": "France",
        "score1": 2,
        "score2": 1,
        "team2": "Sweden"
      },
      {
        "team1": "Mexico",
        "score1": 1,
        "score2": 2,
        "team2": "Ecuador"
      },
      {
        "team1": "England",
        "score1": 1,
        "score2": 0,
        "team2": "DR Congo"
      },
      {
        "team1": "Belgium",
        "score1": 2,
        "score2": 1,
        "team2": "Senegal"
      },
      {
        "team1": "United States",
        "score1": 2,
        "score2": 1,
        "team2": "Bosnia and Herzegovina"
      },
      {
        "team1": "Spain",
        "score1": 2,
        "score2": 1,
        "team2": "Austria"
      },
      {
        "team1": "Portugal",
        "score1": 2,
        "score2": 3,
        "team2": "Croatia"
      },
      {
        "team1": "Switzerland",
        "score1": 3,
        "score2": 2,
        "team2": "Algeria"
      },
      {
        "team1": "Australia",
        "score1": 2,
        "score2": 1,
        "team2": "Egypt"
      },
      {
        "team1": "Argentina",
        "score1": 2,
        "score2": 1,
        "team2": "Cape Verde"
      },
      {
        "team1": "Colombia",
        "score1": 4,
        "score2": 1,
        "team2": "Ghana"
      }
    ],
    "sweet16": [
      {
        "team1": "Canada",
        "score1": 2,
        "score2": 1,
        "team2": "Morocco"
      },
      {
        "team1": "Germany",
        "score1": 2,
        "score2": 1,
        "team2": "France"
      },
      {
        "team1": "Brazil",
        "score1": 2,
        "score2": 1,
        "team2": "Ivory Coast"
      },
      {
        "team1": "Ecuador",
        "score1": 0,
        "score2": 1,
        "team2": "England"
      },
      {
        "team1": "Spain",
        "score1": 1,
        "score2": 0,
        "team2": "Croatia"
      },
      {
        "team1": "United States",
        "score1": 3,
        "score2": 2,
        "team2": "Belgium"
      },
      {
        "team1": "Argentina",
        "score1": 2,
        "score2": 1,
        "team2": "Australia"
      },
      {
        "team1": "Switzerland",
        "score1": 2,
        "score2": 3,
        "team2": "Colombia"
      }
    ],
    "elite8": [
      {
        "team1": "Canada",
        "score1": 2,
        "score2": 3,
        "team2": "Germany"
      },
      {
        "team1": "Spain",
        "score1": 3,
        "score2": 2,
        "team2": "United States"
      },
      {
        "team1": "Brazil",
        "score1": 3,
        "score2": 2,
        "team2": "England"
      },
      {
        "team1": "Argentina",
        "score1": 1,
        "score2": 0,
        "team2": "Colombia"
      }
    ],
    "semis": [
      {
        "team1": "Germany",
        "score1": 0,
        "score2": 2,
        "team2": "Spain"
      },
      {
        "team1": "Brazil",
        "score1": 1,
        "score2": 2,
        "team2": "Argentina"
      }
    ],
    "third": [
      {
        "team1": "Germany",
        "score1": 1,
        "score2": 2,
        "team2": "Brazil"
      }
    ],
    "final": [
      {
        "team1": "Spain",
        "score1": 1,
        "score2": 2,
        "team2": "Argentina"
      }
    ]
  },
  "dav_gpo": {
    "grupos": [],
    "r32": [
      {
        "team1": "South Africa",
        "score1": 0,
        "score2": 1,
        "team2": "Canada"
      },
      {
        "team1": "Brazil",
        "score1": 2,
        "score2": 1,
        "team2": "Japan"
      },
      {
        "team1": "Germany",
        "score1": 2,
        "score2": 1,
        "team2": "Paraguay"
      },
      {
        "team1": "Netherlands",
        "score1": 1,
        "score2": 2,
        "team2": "Morocco"
      },
      {
        "team1": "Ivory Coast",
        "score1": 2,
        "score2": 1,
        "team2": "Norway"
      },
      {
        "team1": "France",
        "score1": 2,
        "score2": 1,
        "team2": "Sweden"
      },
      {
        "team1": "Mexico",
        "score1": 1,
        "score2": 2,
        "team2": "Ecuador"
      },
      {
        "team1": "England",
        "score1": 1,
        "score2": 0,
        "team2": "DR Congo"
      },
      {
        "team1": "Belgium",
        "score1": 2,
        "score2": 1,
        "team2": "Senegal"
      },
      {
        "team1": "United States",
        "score1": 2,
        "score2": 1,
        "team2": "Bosnia and Herzegovina"
      },
      {
        "team1": "Spain",
        "score1": 2,
        "score2": 1,
        "team2": "Austria"
      },
      {
        "team1": "Portugal",
        "score1": 2,
        "score2": 3,
        "team2": "Croatia"
      },
      {
        "team1": "Switzerland",
        "score1": 3,
        "score2": 2,
        "team2": "Algeria"
      },
      {
        "team1": "Australia",
        "score1": 2,
        "score2": 1,
        "team2": "Egypt"
      },
      {
        "team1": "Argentina",
        "score1": 2,
        "score2": 1,
        "team2": "Cape Verde"
      },
      {
        "team1": "Colombia",
        "score1": 4,
        "score2": 1,
        "team2": "Ghana"
      }
    ],
    "sweet16": [
      {
        "team1": "Canada",
        "score1": 2,
        "score2": 1,
        "team2": "Morocco"
      },
      {
        "team1": "Germany",
        "score1": 2,
        "score2": 1,
        "team2": "France"
      },
      {
        "team1": "Brazil",
        "score1": 2,
        "score2": 1,
        "team2": "Ivory Coast"
      },
      {
        "team1": "Ecuador",
        "score1": 0,
        "score2": 1,
        "team2": "England"
      },
      {
        "team1": "Spain",
        "score1": 1,
        "score2": 0,
        "team2": "Croatia"
      },
      {
        "team1": "United States",
        "score1": 3,
        "score2": 2,
        "team2": "Belgium"
      },
      {
        "team1": "Argentina",
        "score1": 2,
        "score2": 1,
        "team2": "Australia"
      },
      {
        "team1": "Switzerland",
        "score1": 2,
        "score2": 3,
        "team2": "Colombia"
      }
    ],
    "elite8": [
      {
        "team1": "Canada",
        "score1": 2,
        "score2": 3,
        "team2": "Germany"
      },
      {
        "team1": "Spain",
        "score1": 3,
        "score2": 2,
        "team2": "United States"
      },
      {
        "team1": "Brazil",
        "score1": 3,
        "score2": 2,
        "team2": "England"
      },
      {
        "team1": "Argentina",
        "score1": 1,
        "score2": 0,
        "team2": "Colombia"
      }
    ],
    "semis": [
      {
        "team1": "Germany",
        "score1": 0,
        "score2": 2,
        "team2": "Spain"
      },
      {
        "team1": "Brazil",
        "score1": 1,
        "score2": 2,
        "team2": "Argentina"
      }
    ],
    "third": [
      {
        "team1": "Germany",
        "score1": 1,
        "score2": 2,
        "team2": "Brazil"
      }
    ],
    "final": [
      {
        "team1": "Spain",
        "score1": 1,
        "score2": 2,
        "team2": "Argentina"
      }
    ]
  }
};
