// AUTO-GENERATED by scripts/export_data.py — do not edit manually

export interface RealResult {
  date: string; homeTeam: string; awayTeam: string;
  homeGoals: number; awayGoals: number;
}

export const realResults: RealResult[] = [
  {
    "date": "2026-06-11",
    "homeTeam": "Mexico",
    "awayTeam": "South Africa",
    "homeGoals": 2,
    "awayGoals": 0
  },
  {
    "date": "2026-06-12",
    "homeTeam": "South Korea",
    "awayTeam": "Czech Republic",
    "homeGoals": 2,
    "awayGoals": 1
  },
  {
    "date": "2026-06-12",
    "homeTeam": "Canada",
    "awayTeam": "Bosnia and Herzegovina",
    "homeGoals": 1,
    "awayGoals": 1
  },
  {
    "date": "2026-06-13",
    "homeTeam": "United States",
    "awayTeam": "Paraguay",
    "homeGoals": 4,
    "awayGoals": 1
  },
  {
    "date": "2026-06-13",
    "homeTeam": "Qatar",
    "awayTeam": "Switzerland",
    "homeGoals": 1,
    "awayGoals": 1
  },
  {
    "date": "2026-06-13",
    "homeTeam": "Brazil",
    "awayTeam": "Morocco",
    "homeGoals": 1,
    "awayGoals": 1
  },
  {
    "date": "2026-06-14",
    "homeTeam": "Haiti",
    "awayTeam": "Scotland",
    "homeGoals": 0,
    "awayGoals": 1
  },
  {
    "date": "2026-06-14",
    "homeTeam": "Australia",
    "awayTeam": "Turkey",
    "homeGoals": 2,
    "awayGoals": 0
  },
  {
    "date": "2026-06-14",
    "homeTeam": "Germany",
    "awayTeam": "Curaçao",
    "homeGoals": 7,
    "awayGoals": 1
  },
  {
    "date": "2026-06-14",
    "homeTeam": "Netherlands",
    "awayTeam": "Japan",
    "homeGoals": 2,
    "awayGoals": 2
  },
  {
    "date": "2026-06-14",
    "homeTeam": "Ivory Coast",
    "awayTeam": "Ecuador",
    "homeGoals": 1,
    "awayGoals": 0
  },
  {
    "date": "2026-06-15",
    "homeTeam": "Sweden",
    "awayTeam": "Tunisia",
    "homeGoals": 5,
    "awayGoals": 1
  },
  {
    "date": "2026-06-15",
    "homeTeam": "Spain",
    "awayTeam": "Cape Verde",
    "homeGoals": 0,
    "awayGoals": 0
  },
  {
    "date": "2026-06-15",
    "homeTeam": "Belgium",
    "awayTeam": "Egypt",
    "homeGoals": 1,
    "awayGoals": 1
  },
  {
    "date": "2026-06-15",
    "homeTeam": "Saudi Arabia",
    "awayTeam": "Uruguay",
    "homeGoals": 1,
    "awayGoals": 1
  },
  {
    "date": "2026-06-16",
    "homeTeam": "Iran",
    "awayTeam": "New Zealand",
    "homeGoals": 2,
    "awayGoals": 2
  },
  {
    "date": "2026-06-16",
    "homeTeam": "France",
    "awayTeam": "Senegal",
    "homeGoals": 3,
    "awayGoals": 1
  },
  {
    "date": "2026-06-16",
    "homeTeam": "Iraq",
    "awayTeam": "Norway",
    "homeGoals": 1,
    "awayGoals": 4
  },
  {
    "date": "2026-06-17",
    "homeTeam": "Argentina",
    "awayTeam": "Algeria",
    "homeGoals": 3,
    "awayGoals": 0
  },
  {
    "date": "2026-06-17",
    "homeTeam": "Austria",
    "awayTeam": "Jordan",
    "homeGoals": 3,
    "awayGoals": 1
  },
  {
    "date": "2026-06-17",
    "homeTeam": "Portugal",
    "awayTeam": "DR Congo",
    "homeGoals": 1,
    "awayGoals": 1
  },
  {
    "date": "2026-06-17",
    "homeTeam": "England",
    "awayTeam": "Croatia",
    "homeGoals": 4,
    "awayGoals": 2
  },
  {
    "date": "2026-06-17",
    "homeTeam": "Ghana",
    "awayTeam": "Panama",
    "homeGoals": 1,
    "awayGoals": 0
  },
  {
    "date": "2026-06-18",
    "homeTeam": "Uzbekistan",
    "awayTeam": "Colombia",
    "homeGoals": 1,
    "awayGoals": 3
  },
  {
    "date": "2026-06-18",
    "homeTeam": "Czech Republic",
    "awayTeam": "South Africa",
    "homeGoals": 1,
    "awayGoals": 1
  },
  {
    "date": "2026-06-18",
    "homeTeam": "Switzerland",
    "awayTeam": "Bosnia and Herzegovina",
    "homeGoals": 4,
    "awayGoals": 1
  },
  {
    "date": "2026-06-18",
    "homeTeam": "Canada",
    "awayTeam": "Qatar",
    "homeGoals": 6,
    "awayGoals": 0
  },
  {
    "date": "2026-06-19",
    "homeTeam": "Mexico",
    "awayTeam": "South Korea",
    "homeGoals": 1,
    "awayGoals": 0
  },
  {
    "date": "2026-06-19",
    "homeTeam": "United States",
    "awayTeam": "Australia",
    "homeGoals": 2,
    "awayGoals": 0
  },
  {
    "date": "2026-06-19",
    "homeTeam": "Scotland",
    "awayTeam": "Morocco",
    "homeGoals": 0,
    "awayGoals": 1
  },
  {
    "date": "2026-06-20",
    "homeTeam": "Brazil",
    "awayTeam": "Haiti",
    "homeGoals": 3,
    "awayGoals": 0
  },
  {
    "date": "2026-06-20",
    "homeTeam": "Turkey",
    "awayTeam": "Paraguay",
    "homeGoals": 0,
    "awayGoals": 1
  },
  {
    "date": "2026-06-20",
    "homeTeam": "Netherlands",
    "awayTeam": "Sweden",
    "homeGoals": 5,
    "awayGoals": 1
  },
  {
    "date": "2026-06-20",
    "homeTeam": "Germany",
    "awayTeam": "Ivory Coast",
    "homeGoals": 2,
    "awayGoals": 1
  },
  {
    "date": "2026-06-21",
    "homeTeam": "Ecuador",
    "awayTeam": "Curaçao",
    "homeGoals": 0,
    "awayGoals": 0
  },
  {
    "date": "2026-06-21",
    "homeTeam": "Tunisia",
    "awayTeam": "Japan",
    "homeGoals": 0,
    "awayGoals": 4
  },
  {
    "date": "2026-06-21",
    "homeTeam": "Spain",
    "awayTeam": "Saudi Arabia",
    "homeGoals": 4,
    "awayGoals": 0
  },
  {
    "date": "2026-06-21",
    "homeTeam": "Belgium",
    "awayTeam": "Iran",
    "homeGoals": 0,
    "awayGoals": 0
  },
  {
    "date": "2026-06-21",
    "homeTeam": "Uruguay",
    "awayTeam": "Cape Verde",
    "homeGoals": 2,
    "awayGoals": 2
  },
  {
    "date": "2026-06-22",
    "homeTeam": "New Zealand",
    "awayTeam": "Egypt",
    "homeGoals": 1,
    "awayGoals": 3
  },
  {
    "date": "2026-06-22",
    "homeTeam": "Argentina",
    "awayTeam": "Austria",
    "homeGoals": 2,
    "awayGoals": 0
  },
  {
    "date": "2026-06-22",
    "homeTeam": "France",
    "awayTeam": "Iraq",
    "homeGoals": 3,
    "awayGoals": 0
  },
  {
    "date": "2026-06-23",
    "homeTeam": "Norway",
    "awayTeam": "Senegal",
    "homeGoals": 3,
    "awayGoals": 2
  },
  {
    "date": "2026-06-23",
    "homeTeam": "Jordan",
    "awayTeam": "Algeria",
    "homeGoals": 1,
    "awayGoals": 2
  },
  {
    "date": "2026-06-23",
    "homeTeam": "Portugal",
    "awayTeam": "Uzbekistan",
    "homeGoals": 5,
    "awayGoals": 0
  },
  {
    "date": "2026-06-23",
    "homeTeam": "England",
    "awayTeam": "Ghana",
    "homeGoals": 0,
    "awayGoals": 0
  },
  {
    "date": "2026-06-23",
    "homeTeam": "Panama",
    "awayTeam": "Croatia",
    "homeGoals": 0,
    "awayGoals": 1
  },
  {
    "date": "2026-06-24",
    "homeTeam": "Colombia",
    "awayTeam": "DR Congo",
    "homeGoals": 1,
    "awayGoals": 0
  }
];
