// AUTO-GENERATED by scripts/export_data.py — do not edit manually

export interface RealResult {
  date: string; homeTeam: string; awayTeam: string;
  homeGoals: number; awayGoals: number;
}

export const realResults: RealResult[] = [];
