// AUTO-GENERATED by scripts/export_data.py — do not edit manually

import type { Variant } from './predictions';

export interface XGEntry { team: string; opponent: string; xg: number; }

export const xgData: Record<Variant, { J1: XGEntry[]; J2: XGEntry[]; J3: XGEntry[] }> = {
  "misterclaude": {
    "J1": [
      {
        "team": "Czech Republic",
        "opponent": "South Korea",
        "xg": 0.98
      },
      {
        "team": "Mexico",
        "opponent": "South Africa",
        "xg": 2.01
      },
      {
        "team": "South Africa",
        "opponent": "Mexico",
        "xg": 0.59
      },
      {
        "team": "South Korea",
        "opponent": "Czech Republic",
        "xg": 1.18
      },
      {
        "team": "Bosnia and Herzegovina",
        "opponent": "Canada",
        "xg": 0.68
      },
      {
        "team": "Canada",
        "opponent": "Bosnia and Herzegovina",
        "xg": 1.78
      },
      {
        "team": "Paraguay",
        "opponent": "United States",
        "xg": 1.18
      },
      {
        "team": "United States",
        "opponent": "Paraguay",
        "xg": 1.22
      },
      {
        "team": "Australia",
        "opponent": "Turkey",
        "xg": 0.96
      },
      {
        "team": "Brazil",
        "opponent": "Morocco",
        "xg": 1.16
      },
      {
        "team": "Haiti",
        "opponent": "Scotland",
        "xg": 0.72
      },
      {
        "team": "Morocco",
        "opponent": "Brazil",
        "xg": 0.92
      },
      {
        "team": "Qatar",
        "opponent": "Switzerland",
        "xg": 0.57
      },
      {
        "team": "Scotland",
        "opponent": "Haiti",
        "xg": 1.45
      },
      {
        "team": "Switzerland",
        "opponent": "Qatar",
        "xg": 2.06
      },
      {
        "team": "Turkey",
        "opponent": "Australia",
        "xg": 1.35
      },
      {
        "team": "Curaçao",
        "opponent": "Germany",
        "xg": 0.42
      },
      {
        "team": "Ecuador",
        "opponent": "Ivory Coast",
        "xg": 1.09
      },
      {
        "team": "Germany",
        "opponent": "Curaçao",
        "xg": 2.84
      },
      {
        "team": "Ivory Coast",
        "opponent": "Ecuador",
        "xg": 0.62
      },
      {
        "team": "Japan",
        "opponent": "Netherlands",
        "xg": 1.0
      },
      {
        "team": "Netherlands",
        "opponent": "Japan",
        "xg": 1.11
      },
      {
        "team": "Sweden",
        "opponent": "Tunisia",
        "xg": 1.4
      },
      {
        "team": "Tunisia",
        "opponent": "Sweden",
        "xg": 0.93
      },
      {
        "team": "Belgium",
        "opponent": "Egypt",
        "xg": 1.25
      },
      {
        "team": "Cape Verde",
        "opponent": "Spain",
        "xg": 0.58
      },
      {
        "team": "Egypt",
        "opponent": "Belgium",
        "xg": 0.84
      },
      {
        "team": "Iran",
        "opponent": "New Zealand",
        "xg": 1.51
      },
      {
        "team": "New Zealand",
        "opponent": "Iran",
        "xg": 0.69
      },
      {
        "team": "Saudi Arabia",
        "opponent": "Uruguay",
        "xg": 0.63
      },
      {
        "team": "Spain",
        "opponent": "Cape Verde",
        "xg": 1.87
      },
      {
        "team": "Uruguay",
        "opponent": "Saudi Arabia",
        "xg": 1.45
      },
      {
        "team": "Algeria",
        "opponent": "Argentina",
        "xg": 0.75
      },
      {
        "team": "Argentina",
        "opponent": "Algeria",
        "xg": 1.47
      },
      {
        "team": "Austria",
        "opponent": "Jordan",
        "xg": 1.54
      },
      {
        "team": "France",
        "opponent": "Senegal",
        "xg": 1.46
      },
      {
        "team": "Iraq",
        "opponent": "Norway",
        "xg": 0.61
      },
      {
        "team": "Jordan",
        "opponent": "Austria",
        "xg": 0.76
      },
      {
        "team": "Norway",
        "opponent": "Iraq",
        "xg": 1.46
      },
      {
        "team": "Senegal",
        "opponent": "France",
        "xg": 0.89
      },
      {
        "team": "Colombia",
        "opponent": "Uzbekistan",
        "xg": 1.4
      },
      {
        "team": "Croatia",
        "opponent": "England",
        "xg": 1.0
      },
      {
        "team": "DR Congo",
        "opponent": "Portugal",
        "xg": 0.69
      },
      {
        "team": "England",
        "opponent": "Croatia",
        "xg": 1.59
      },
      {
        "team": "Ghana",
        "opponent": "Panama",
        "xg": 0.67
      },
      {
        "team": "Panama",
        "opponent": "Ghana",
        "xg": 1.45
      },
      {
        "team": "Portugal",
        "opponent": "DR Congo",
        "xg": 1.4
      },
      {
        "team": "Uzbekistan",
        "opponent": "Colombia",
        "xg": 0.74
      }
    ],
    "J2": [
      {
        "team": "Bosnia and Herzegovina",
        "opponent": "Switzerland",
        "xg": 0.78
      },
      {
        "team": "Canada",
        "opponent": "Qatar",
        "xg": 2.3
      },
      {
        "team": "Czech Republic",
        "opponent": "South Africa",
        "xg": 1.35
      },
      {
        "team": "Mexico",
        "opponent": "South Korea",
        "xg": 1.34
      },
      {
        "team": "Qatar",
        "opponent": "Canada",
        "xg": 0.54
      },
      {
        "team": "South Africa",
        "opponent": "Czech Republic",
        "xg": 0.78
      },
      {
        "team": "South Korea",
        "opponent": "Mexico",
        "xg": 0.84
      },
      {
        "team": "Switzerland",
        "opponent": "Bosnia and Herzegovina",
        "xg": 1.62
      },
      {
        "team": "Australia",
        "opponent": "United States",
        "xg": 1.19
      },
      {
        "team": "Brazil",
        "opponent": "Haiti",
        "xg": 1.81
      },
      {
        "team": "Haiti",
        "opponent": "Brazil",
        "xg": 0.58
      },
      {
        "team": "Morocco",
        "opponent": "Scotland",
        "xg": 1.25
      },
      {
        "team": "Paraguay",
        "opponent": "Turkey",
        "xg": 0.95
      },
      {
        "team": "Scotland",
        "opponent": "Morocco",
        "xg": 0.8
      },
      {
        "team": "Turkey",
        "opponent": "Paraguay",
        "xg": 1.37
      },
      {
        "team": "United States",
        "opponent": "Australia",
        "xg": 1.25
      },
      {
        "team": "Curaçao",
        "opponent": "Ecuador",
        "xg": 0.36
      },
      {
        "team": "Ecuador",
        "opponent": "Curaçao",
        "xg": 2.38
      },
      {
        "team": "Germany",
        "opponent": "Ivory Coast",
        "xg": 1.39
      },
      {
        "team": "Ivory Coast",
        "opponent": "Germany",
        "xg": 0.78
      },
      {
        "team": "Japan",
        "opponent": "Tunisia",
        "xg": 1.59
      },
      {
        "team": "Netherlands",
        "opponent": "Sweden",
        "xg": 1.83
      },
      {
        "team": "Sweden",
        "opponent": "Netherlands",
        "xg": 0.88
      },
      {
        "team": "Tunisia",
        "opponent": "Japan",
        "xg": 0.58
      },
      {
        "team": "Belgium",
        "opponent": "Iran",
        "xg": 1.2
      },
      {
        "team": "Cape Verde",
        "opponent": "Uruguay",
        "xg": 0.65
      },
      {
        "team": "Egypt",
        "opponent": "New Zealand",
        "xg": 1.16
      },
      {
        "team": "Iran",
        "opponent": "Belgium",
        "xg": 1.03
      },
      {
        "team": "New Zealand",
        "opponent": "Egypt",
        "xg": 0.76
      },
      {
        "team": "Saudi Arabia",
        "opponent": "Spain",
        "xg": 0.54
      },
      {
        "team": "Spain",
        "opponent": "Saudi Arabia",
        "xg": 2.05
      },
      {
        "team": "Uruguay",
        "opponent": "Cape Verde",
        "xg": 1.42
      },
      {
        "team": "Algeria",
        "opponent": "Jordan",
        "xg": 1.33
      },
      {
        "team": "Argentina",
        "opponent": "Austria",
        "xg": 1.62
      },
      {
        "team": "Austria",
        "opponent": "Argentina",
        "xg": 0.85
      },
      {
        "team": "France",
        "opponent": "Iraq",
        "xg": 1.86
      },
      {
        "team": "Iraq",
        "opponent": "France",
        "xg": 0.57
      },
      {
        "team": "Jordan",
        "opponent": "Algeria",
        "xg": 0.72
      },
      {
        "team": "Norway",
        "opponent": "Senegal",
        "xg": 1.06
      },
      {
        "team": "Senegal",
        "opponent": "Norway",
        "xg": 0.95
      },
      {
        "team": "Colombia",
        "opponent": "DR Congo",
        "xg": 1.34
      },
      {
        "team": "Croatia",
        "opponent": "Panama",
        "xg": 1.48
      },
      {
        "team": "DR Congo",
        "opponent": "Colombia",
        "xg": 0.69
      },
      {
        "team": "England",
        "opponent": "Ghana",
        "xg": 2.08
      },
      {
        "team": "Ghana",
        "opponent": "England",
        "xg": 0.46
      },
      {
        "team": "Panama",
        "opponent": "Croatia",
        "xg": 1.02
      },
      {
        "team": "Portugal",
        "opponent": "Uzbekistan",
        "xg": 1.44
      },
      {
        "team": "Uzbekistan",
        "opponent": "Portugal",
        "xg": 0.75
      }
    ],
    "J3": [
      {
        "team": "Bosnia and Herzegovina",
        "opponent": "Qatar",
        "xg": 1.37
      },
      {
        "team": "Brazil",
        "opponent": "Scotland",
        "xg": 1.6
      },
      {
        "team": "Canada",
        "opponent": "Switzerland",
        "xg": 1.26
      },
      {
        "team": "Czech Republic",
        "opponent": "Mexico",
        "xg": 0.82
      },
      {
        "team": "Haiti",
        "opponent": "Morocco",
        "xg": 0.52
      },
      {
        "team": "Mexico",
        "opponent": "Czech Republic",
        "xg": 1.5
      },
      {
        "team": "Morocco",
        "opponent": "Haiti",
        "xg": 1.57
      },
      {
        "team": "Qatar",
        "opponent": "Bosnia and Herzegovina",
        "xg": 0.84
      },
      {
        "team": "Scotland",
        "opponent": "Brazil",
        "xg": 0.83
      },
      {
        "team": "South Africa",
        "opponent": "South Korea",
        "xg": 0.66
      },
      {
        "team": "South Korea",
        "opponent": "South Africa",
        "xg": 1.48
      },
      {
        "team": "Switzerland",
        "opponent": "Canada",
        "xg": 1.11
      },
      {
        "team": "Australia",
        "opponent": "Paraguay",
        "xg": 0.98
      },
      {
        "team": "Curaçao",
        "opponent": "Ivory Coast",
        "xg": 0.47
      },
      {
        "team": "Ecuador",
        "opponent": "Germany",
        "xg": 1.0
      },
      {
        "team": "Germany",
        "opponent": "Ecuador",
        "xg": 1.04
      },
      {
        "team": "Ivory Coast",
        "opponent": "Curaçao",
        "xg": 1.82
      },
      {
        "team": "Japan",
        "opponent": "Sweden",
        "xg": 1.44
      },
      {
        "team": "Netherlands",
        "opponent": "Tunisia",
        "xg": 1.83
      },
      {
        "team": "Paraguay",
        "opponent": "Australia",
        "xg": 1.01
      },
      {
        "team": "Sweden",
        "opponent": "Japan",
        "xg": 0.77
      },
      {
        "team": "Tunisia",
        "opponent": "Netherlands",
        "xg": 0.68
      },
      {
        "team": "Turkey",
        "opponent": "United States",
        "xg": 1.64
      },
      {
        "team": "United States",
        "opponent": "Turkey",
        "xg": 1.26
      },
      {
        "team": "Belgium",
        "opponent": "New Zealand",
        "xg": 1.85
      },
      {
        "team": "Cape Verde",
        "opponent": "Saudi Arabia",
        "xg": 1.06
      },
      {
        "team": "Egypt",
        "opponent": "Iran",
        "xg": 0.79
      },
      {
        "team": "France",
        "opponent": "Norway",
        "xg": 1.4
      },
      {
        "team": "Iran",
        "opponent": "Egypt",
        "xg": 1.0
      },
      {
        "team": "Iraq",
        "opponent": "Senegal",
        "xg": 0.62
      },
      {
        "team": "New Zealand",
        "opponent": "Belgium",
        "xg": 0.82
      },
      {
        "team": "Norway",
        "opponent": "France",
        "xg": 0.98
      },
      {
        "team": "Saudi Arabia",
        "opponent": "Cape Verde",
        "xg": 0.98
      },
      {
        "team": "Senegal",
        "opponent": "Iraq",
        "xg": 1.31
      },
      {
        "team": "Spain",
        "opponent": "Uruguay",
        "xg": 1.35
      },
      {
        "team": "Uruguay",
        "opponent": "Spain",
        "xg": 0.81
      },
      {
        "team": "Algeria",
        "opponent": "Austria",
        "xg": 0.97
      },
      {
        "team": "Argentina",
        "opponent": "Jordan",
        "xg": 1.99
      },
      {
        "team": "Austria",
        "opponent": "Algeria",
        "xg": 1.03
      },
      {
        "team": "Colombia",
        "opponent": "Portugal",
        "xg": 1.28
      },
      {
        "team": "Croatia",
        "opponent": "Ghana",
        "xg": 1.92
      },
      {
        "team": "DR Congo",
        "opponent": "Uzbekistan",
        "xg": 0.77
      },
      {
        "team": "England",
        "opponent": "Panama",
        "xg": 1.53
      },
      {
        "team": "Ghana",
        "opponent": "Croatia",
        "xg": 0.7
      },
      {
        "team": "Jordan",
        "opponent": "Argentina",
        "xg": 0.62
      },
      {
        "team": "Panama",
        "opponent": "England",
        "xg": 0.67
      },
      {
        "team": "Portugal",
        "opponent": "Colombia",
        "xg": 1.34
      },
      {
        "team": "Uzbekistan",
        "opponent": "DR Congo",
        "xg": 0.92
      }
    ]
  },
  "gemaldini": {
    "J1": [
      {
        "team": "Czech Republic",
        "opponent": "South Korea",
        "xg": 1.14
      },
      {
        "team": "Mexico",
        "opponent": "South Africa",
        "xg": 2.01
      },
      {
        "team": "South Africa",
        "opponent": "Mexico",
        "xg": 0.59
      },
      {
        "team": "South Korea",
        "opponent": "Czech Republic",
        "xg": 1.04
      },
      {
        "team": "Bosnia and Herzegovina",
        "opponent": "Canada",
        "xg": 0.92
      },
      {
        "team": "Canada",
        "opponent": "Bosnia and Herzegovina",
        "xg": 1.52
      },
      {
        "team": "Paraguay",
        "opponent": "United States",
        "xg": 1.18
      },
      {
        "team": "United States",
        "opponent": "Paraguay",
        "xg": 1.22
      },
      {
        "team": "Australia",
        "opponent": "Turkey",
        "xg": 0.9
      },
      {
        "team": "Brazil",
        "opponent": "Morocco",
        "xg": 1.16
      },
      {
        "team": "Haiti",
        "opponent": "Scotland",
        "xg": 0.67
      },
      {
        "team": "Morocco",
        "opponent": "Brazil",
        "xg": 0.92
      },
      {
        "team": "Qatar",
        "opponent": "Switzerland",
        "xg": 0.52
      },
      {
        "team": "Scotland",
        "opponent": "Haiti",
        "xg": 1.62
      },
      {
        "team": "Switzerland",
        "opponent": "Qatar",
        "xg": 2.24
      },
      {
        "team": "Turkey",
        "opponent": "Australia",
        "xg": 1.43
      },
      {
        "team": "Curaçao",
        "opponent": "Germany",
        "xg": 0.39
      },
      {
        "team": "Ecuador",
        "opponent": "Ivory Coast",
        "xg": 1.09
      },
      {
        "team": "Germany",
        "opponent": "Curaçao",
        "xg": 2.89
      },
      {
        "team": "Ivory Coast",
        "opponent": "Ecuador",
        "xg": 0.62
      },
      {
        "team": "Japan",
        "opponent": "Netherlands",
        "xg": 0.96
      },
      {
        "team": "Netherlands",
        "opponent": "Japan",
        "xg": 1.11
      },
      {
        "team": "Sweden",
        "opponent": "Tunisia",
        "xg": 1.58
      },
      {
        "team": "Tunisia",
        "opponent": "Sweden",
        "xg": 0.86
      },
      {
        "team": "Belgium",
        "opponent": "Egypt",
        "xg": 1.53
      },
      {
        "team": "Cape Verde",
        "opponent": "Spain",
        "xg": 0.58
      },
      {
        "team": "Egypt",
        "opponent": "Belgium",
        "xg": 0.73
      },
      {
        "team": "Iran",
        "opponent": "New Zealand",
        "xg": 1.51
      },
      {
        "team": "New Zealand",
        "opponent": "Iran",
        "xg": 0.69
      },
      {
        "team": "Saudi Arabia",
        "opponent": "Uruguay",
        "xg": 0.63
      },
      {
        "team": "Spain",
        "opponent": "Cape Verde",
        "xg": 1.87
      },
      {
        "team": "Uruguay",
        "opponent": "Saudi Arabia",
        "xg": 1.45
      },
      {
        "team": "Algeria",
        "opponent": "Argentina",
        "xg": 0.75
      },
      {
        "team": "Argentina",
        "opponent": "Algeria",
        "xg": 1.47
      },
      {
        "team": "Austria",
        "opponent": "Jordan",
        "xg": 1.82
      },
      {
        "team": "France",
        "opponent": "Senegal",
        "xg": 1.47
      },
      {
        "team": "Iraq",
        "opponent": "Norway",
        "xg": 0.54
      },
      {
        "team": "Jordan",
        "opponent": "Austria",
        "xg": 0.72
      },
      {
        "team": "Norway",
        "opponent": "Iraq",
        "xg": 1.75
      },
      {
        "team": "Senegal",
        "opponent": "France",
        "xg": 0.86
      },
      {
        "team": "Colombia",
        "opponent": "Uzbekistan",
        "xg": 1.4
      },
      {
        "team": "Croatia",
        "opponent": "England",
        "xg": 1.07
      },
      {
        "team": "DR Congo",
        "opponent": "Portugal",
        "xg": 0.65
      },
      {
        "team": "England",
        "opponent": "Croatia",
        "xg": 1.59
      },
      {
        "team": "Ghana",
        "opponent": "Panama",
        "xg": 0.67
      },
      {
        "team": "Panama",
        "opponent": "Ghana",
        "xg": 1.45
      },
      {
        "team": "Portugal",
        "opponent": "DR Congo",
        "xg": 1.45
      },
      {
        "team": "Uzbekistan",
        "opponent": "Colombia",
        "xg": 0.74
      }
    ],
    "J2": [
      {
        "team": "Bosnia and Herzegovina",
        "opponent": "Switzerland",
        "xg": 0.72
      },
      {
        "team": "Canada",
        "opponent": "Qatar",
        "xg": 2.3
      },
      {
        "team": "Czech Republic",
        "opponent": "South Africa",
        "xg": 1.56
      },
      {
        "team": "Mexico",
        "opponent": "South Korea",
        "xg": 1.34
      },
      {
        "team": "Qatar",
        "opponent": "Canada",
        "xg": 0.54
      },
      {
        "team": "South Africa",
        "opponent": "Czech Republic",
        "xg": 0.72
      },
      {
        "team": "South Korea",
        "opponent": "Mexico",
        "xg": 0.84
      },
      {
        "team": "Switzerland",
        "opponent": "Bosnia and Herzegovina",
        "xg": 1.86
      },
      {
        "team": "Australia",
        "opponent": "United States",
        "xg": 1.19
      },
      {
        "team": "Brazil",
        "opponent": "Haiti",
        "xg": 1.81
      },
      {
        "team": "Haiti",
        "opponent": "Brazil",
        "xg": 0.58
      },
      {
        "team": "Morocco",
        "opponent": "Scotland",
        "xg": 1.12
      },
      {
        "team": "Paraguay",
        "opponent": "Turkey",
        "xg": 0.85
      },
      {
        "team": "Scotland",
        "opponent": "Morocco",
        "xg": 0.89
      },
      {
        "team": "Turkey",
        "opponent": "Paraguay",
        "xg": 1.47
      },
      {
        "team": "United States",
        "opponent": "Australia",
        "xg": 1.25
      },
      {
        "team": "Curaçao",
        "opponent": "Ecuador",
        "xg": 0.36
      },
      {
        "team": "Ecuador",
        "opponent": "Curaçao",
        "xg": 2.38
      },
      {
        "team": "Germany",
        "opponent": "Ivory Coast",
        "xg": 1.43
      },
      {
        "team": "Ivory Coast",
        "opponent": "Germany",
        "xg": 0.74
      },
      {
        "team": "Japan",
        "opponent": "Tunisia",
        "xg": 1.59
      },
      {
        "team": "Netherlands",
        "opponent": "Sweden",
        "xg": 1.82
      },
      {
        "team": "Sweden",
        "opponent": "Netherlands",
        "xg": 0.84
      },
      {
        "team": "Tunisia",
        "opponent": "Japan",
        "xg": 0.58
      },
      {
        "team": "Belgium",
        "opponent": "Iran",
        "xg": 1.52
      },
      {
        "team": "Cape Verde",
        "opponent": "Uruguay",
        "xg": 0.65
      },
      {
        "team": "Egypt",
        "opponent": "New Zealand",
        "xg": 1.16
      },
      {
        "team": "Iran",
        "opponent": "Belgium",
        "xg": 0.94
      },
      {
        "team": "New Zealand",
        "opponent": "Egypt",
        "xg": 0.76
      },
      {
        "team": "Saudi Arabia",
        "opponent": "Spain",
        "xg": 0.54
      },
      {
        "team": "Spain",
        "opponent": "Saudi Arabia",
        "xg": 2.05
      },
      {
        "team": "Uruguay",
        "opponent": "Cape Verde",
        "xg": 1.42
      },
      {
        "team": "Algeria",
        "opponent": "Jordan",
        "xg": 1.33
      },
      {
        "team": "Argentina",
        "opponent": "Austria",
        "xg": 1.44
      },
      {
        "team": "Austria",
        "opponent": "Argentina",
        "xg": 1.08
      },
      {
        "team": "France",
        "opponent": "Iraq",
        "xg": 1.89
      },
      {
        "team": "Iraq",
        "opponent": "France",
        "xg": 0.53
      },
      {
        "team": "Jordan",
        "opponent": "Algeria",
        "xg": 0.72
      },
      {
        "team": "Norway",
        "opponent": "Senegal",
        "xg": 1.37
      },
      {
        "team": "Senegal",
        "opponent": "Norway",
        "xg": 0.84
      },
      {
        "team": "Colombia",
        "opponent": "DR Congo",
        "xg": 1.34
      },
      {
        "team": "Croatia",
        "opponent": "Panama",
        "xg": 1.56
      },
      {
        "team": "DR Congo",
        "opponent": "Colombia",
        "xg": 0.69
      },
      {
        "team": "England",
        "opponent": "Ghana",
        "xg": 2.1
      },
      {
        "team": "Ghana",
        "opponent": "England",
        "xg": 0.42
      },
      {
        "team": "Panama",
        "opponent": "Croatia",
        "xg": 0.96
      },
      {
        "team": "Portugal",
        "opponent": "Uzbekistan",
        "xg": 1.48
      },
      {
        "team": "Uzbekistan",
        "opponent": "Portugal",
        "xg": 0.72
      }
    ],
    "J3": [
      {
        "team": "Bosnia and Herzegovina",
        "opponent": "Qatar",
        "xg": 1.65
      },
      {
        "team": "Brazil",
        "opponent": "Scotland",
        "xg": 1.45
      },
      {
        "team": "Canada",
        "opponent": "Switzerland",
        "xg": 1.05
      },
      {
        "team": "Czech Republic",
        "opponent": "Mexico",
        "xg": 0.94
      },
      {
        "team": "Haiti",
        "opponent": "Morocco",
        "xg": 0.52
      },
      {
        "team": "Mexico",
        "opponent": "Czech Republic",
        "xg": 1.33
      },
      {
        "team": "Morocco",
        "opponent": "Haiti",
        "xg": 1.57
      },
      {
        "team": "Qatar",
        "opponent": "Bosnia and Herzegovina",
        "xg": 0.71
      },
      {
        "team": "Scotland",
        "opponent": "Brazil",
        "xg": 0.93
      },
      {
        "team": "South Africa",
        "opponent": "South Korea",
        "xg": 0.66
      },
      {
        "team": "South Korea",
        "opponent": "South Africa",
        "xg": 1.48
      },
      {
        "team": "Switzerland",
        "opponent": "Canada",
        "xg": 1.37
      },
      {
        "team": "Australia",
        "opponent": "Paraguay",
        "xg": 0.98
      },
      {
        "team": "Curaçao",
        "opponent": "Ivory Coast",
        "xg": 0.47
      },
      {
        "team": "Ecuador",
        "opponent": "Germany",
        "xg": 0.95
      },
      {
        "team": "Germany",
        "opponent": "Ecuador",
        "xg": 1.08
      },
      {
        "team": "Ivory Coast",
        "opponent": "Curaçao",
        "xg": 1.82
      },
      {
        "team": "Japan",
        "opponent": "Sweden",
        "xg": 1.28
      },
      {
        "team": "Netherlands",
        "opponent": "Tunisia",
        "xg": 1.82
      },
      {
        "team": "Paraguay",
        "opponent": "Australia",
        "xg": 1.01
      },
      {
        "team": "Sweden",
        "opponent": "Japan",
        "xg": 0.86
      },
      {
        "team": "Tunisia",
        "opponent": "Netherlands",
        "xg": 0.66
      },
      {
        "team": "Turkey",
        "opponent": "United States",
        "xg": 1.71
      },
      {
        "team": "United States",
        "opponent": "Turkey",
        "xg": 1.05
      },
      {
        "team": "Belgium",
        "opponent": "New Zealand",
        "xg": 2.06
      },
      {
        "team": "Cape Verde",
        "opponent": "Saudi Arabia",
        "xg": 1.06
      },
      {
        "team": "Egypt",
        "opponent": "Iran",
        "xg": 0.79
      },
      {
        "team": "France",
        "opponent": "Norway",
        "xg": 1.27
      },
      {
        "team": "Iran",
        "opponent": "Egypt",
        "xg": 1.0
      },
      {
        "team": "Iraq",
        "opponent": "Senegal",
        "xg": 0.62
      },
      {
        "team": "New Zealand",
        "opponent": "Belgium",
        "xg": 0.75
      },
      {
        "team": "Norway",
        "opponent": "France",
        "xg": 1.27
      },
      {
        "team": "Saudi Arabia",
        "opponent": "Cape Verde",
        "xg": 0.98
      },
      {
        "team": "Senegal",
        "opponent": "Iraq",
        "xg": 1.31
      },
      {
        "team": "Spain",
        "opponent": "Uruguay",
        "xg": 1.35
      },
      {
        "team": "Uruguay",
        "opponent": "Spain",
        "xg": 0.81
      },
      {
        "team": "Algeria",
        "opponent": "Austria",
        "xg": 0.9
      },
      {
        "team": "Argentina",
        "opponent": "Jordan",
        "xg": 1.99
      },
      {
        "team": "Austria",
        "opponent": "Algeria",
        "xg": 1.31
      },
      {
        "team": "Colombia",
        "opponent": "Portugal",
        "xg": 1.22
      },
      {
        "team": "Croatia",
        "opponent": "Ghana",
        "xg": 2.04
      },
      {
        "team": "DR Congo",
        "opponent": "Uzbekistan",
        "xg": 0.77
      },
      {
        "team": "England",
        "opponent": "Panama",
        "xg": 1.54
      },
      {
        "team": "Ghana",
        "opponent": "Croatia",
        "xg": 0.65
      },
      {
        "team": "Jordan",
        "opponent": "Argentina",
        "xg": 0.62
      },
      {
        "team": "Panama",
        "opponent": "England",
        "xg": 0.61
      },
      {
        "team": "Portugal",
        "opponent": "Colombia",
        "xg": 1.4
      },
      {
        "team": "Uzbekistan",
        "opponent": "DR Congo",
        "xg": 0.92
      }
    ]
  },
  "dav_gpo": {
    "J1": [
      {
        "team": "Czech Republic",
        "opponent": "South Korea",
        "xg": 0.98
      },
      {
        "team": "Mexico",
        "opponent": "South Africa",
        "xg": 2.31
      },
      {
        "team": "South Africa",
        "opponent": "Mexico",
        "xg": 0.55
      },
      {
        "team": "South Korea",
        "opponent": "Czech Republic",
        "xg": 1.18
      },
      {
        "team": "Bosnia and Herzegovina",
        "opponent": "Canada",
        "xg": 0.68
      },
      {
        "team": "Canada",
        "opponent": "Bosnia and Herzegovina",
        "xg": 1.78
      },
      {
        "team": "Paraguay",
        "opponent": "United States",
        "xg": 1.46
      },
      {
        "team": "United States",
        "opponent": "Paraguay",
        "xg": 1.0
      },
      {
        "team": "Australia",
        "opponent": "Turkey",
        "xg": 0.96
      },
      {
        "team": "Brazil",
        "opponent": "Morocco",
        "xg": 1.2
      },
      {
        "team": "Haiti",
        "opponent": "Scotland",
        "xg": 0.72
      },
      {
        "team": "Morocco",
        "opponent": "Brazil",
        "xg": 0.87
      },
      {
        "team": "Qatar",
        "opponent": "Switzerland",
        "xg": 0.57
      },
      {
        "team": "Scotland",
        "opponent": "Haiti",
        "xg": 1.45
      },
      {
        "team": "Switzerland",
        "opponent": "Qatar",
        "xg": 2.06
      },
      {
        "team": "Turkey",
        "opponent": "Australia",
        "xg": 1.35
      },
      {
        "team": "Curaçao",
        "opponent": "Germany",
        "xg": 0.42
      },
      {
        "team": "Ecuador",
        "opponent": "Ivory Coast",
        "xg": 1.17
      },
      {
        "team": "Germany",
        "opponent": "Curaçao",
        "xg": 2.84
      },
      {
        "team": "Ivory Coast",
        "opponent": "Ecuador",
        "xg": 0.56
      },
      {
        "team": "Japan",
        "opponent": "Netherlands",
        "xg": 1.0
      },
      {
        "team": "Netherlands",
        "opponent": "Japan",
        "xg": 1.11
      },
      {
        "team": "Sweden",
        "opponent": "Tunisia",
        "xg": 1.4
      },
      {
        "team": "Tunisia",
        "opponent": "Sweden",
        "xg": 0.93
      },
      {
        "team": "Belgium",
        "opponent": "Egypt",
        "xg": 1.25
      },
      {
        "team": "Cape Verde",
        "opponent": "Spain",
        "xg": 0.58
      },
      {
        "team": "Egypt",
        "opponent": "Belgium",
        "xg": 0.84
      },
      {
        "team": "Iran",
        "opponent": "New Zealand",
        "xg": 1.51
      },
      {
        "team": "New Zealand",
        "opponent": "Iran",
        "xg": 0.69
      },
      {
        "team": "Saudi Arabia",
        "opponent": "Uruguay",
        "xg": 0.58
      },
      {
        "team": "Spain",
        "opponent": "Cape Verde",
        "xg": 1.87
      },
      {
        "team": "Uruguay",
        "opponent": "Saudi Arabia",
        "xg": 1.53
      },
      {
        "team": "Algeria",
        "opponent": "Argentina",
        "xg": 0.72
      },
      {
        "team": "Argentina",
        "opponent": "Algeria",
        "xg": 1.48
      },
      {
        "team": "Austria",
        "opponent": "Jordan",
        "xg": 1.54
      },
      {
        "team": "France",
        "opponent": "Senegal",
        "xg": 1.46
      },
      {
        "team": "Iraq",
        "opponent": "Norway",
        "xg": 0.61
      },
      {
        "team": "Jordan",
        "opponent": "Austria",
        "xg": 0.76
      },
      {
        "team": "Norway",
        "opponent": "Iraq",
        "xg": 1.46
      },
      {
        "team": "Senegal",
        "opponent": "France",
        "xg": 0.89
      },
      {
        "team": "Colombia",
        "opponent": "Uzbekistan",
        "xg": 1.46
      },
      {
        "team": "Croatia",
        "opponent": "England",
        "xg": 1.0
      },
      {
        "team": "DR Congo",
        "opponent": "Portugal",
        "xg": 0.69
      },
      {
        "team": "England",
        "opponent": "Croatia",
        "xg": 1.59
      },
      {
        "team": "Ghana",
        "opponent": "Panama",
        "xg": 0.62
      },
      {
        "team": "Panama",
        "opponent": "Ghana",
        "xg": 1.71
      },
      {
        "team": "Portugal",
        "opponent": "DR Congo",
        "xg": 1.4
      },
      {
        "team": "Uzbekistan",
        "opponent": "Colombia",
        "xg": 0.71
      }
    ],
    "J2": [
      {
        "team": "Bosnia and Herzegovina",
        "opponent": "Switzerland",
        "xg": 0.78
      },
      {
        "team": "Canada",
        "opponent": "Qatar",
        "xg": 2.3
      },
      {
        "team": "Czech Republic",
        "opponent": "South Africa",
        "xg": 1.35
      },
      {
        "team": "Mexico",
        "opponent": "South Korea",
        "xg": 1.7
      },
      {
        "team": "Qatar",
        "opponent": "Canada",
        "xg": 0.54
      },
      {
        "team": "South Africa",
        "opponent": "Czech Republic",
        "xg": 0.78
      },
      {
        "team": "South Korea",
        "opponent": "Mexico",
        "xg": 0.76
      },
      {
        "team": "Switzerland",
        "opponent": "Bosnia and Herzegovina",
        "xg": 1.62
      },
      {
        "team": "Australia",
        "opponent": "United States",
        "xg": 1.19
      },
      {
        "team": "Brazil",
        "opponent": "Haiti",
        "xg": 1.84
      },
      {
        "team": "Haiti",
        "opponent": "Brazil",
        "xg": 0.54
      },
      {
        "team": "Morocco",
        "opponent": "Scotland",
        "xg": 1.25
      },
      {
        "team": "Paraguay",
        "opponent": "Turkey",
        "xg": 1.22
      },
      {
        "team": "Scotland",
        "opponent": "Morocco",
        "xg": 0.8
      },
      {
        "team": "Turkey",
        "opponent": "Paraguay",
        "xg": 1.22
      },
      {
        "team": "United States",
        "opponent": "Australia",
        "xg": 1.25
      },
      {
        "team": "Curaçao",
        "opponent": "Ecuador",
        "xg": 0.32
      },
      {
        "team": "Ecuador",
        "opponent": "Curaçao",
        "xg": 2.52
      },
      {
        "team": "Germany",
        "opponent": "Ivory Coast",
        "xg": 1.39
      },
      {
        "team": "Ivory Coast",
        "opponent": "Germany",
        "xg": 0.78
      },
      {
        "team": "Japan",
        "opponent": "Tunisia",
        "xg": 1.59
      },
      {
        "team": "Netherlands",
        "opponent": "Sweden",
        "xg": 1.83
      },
      {
        "team": "Sweden",
        "opponent": "Netherlands",
        "xg": 0.88
      },
      {
        "team": "Tunisia",
        "opponent": "Japan",
        "xg": 0.58
      },
      {
        "team": "Belgium",
        "opponent": "Iran",
        "xg": 1.2
      },
      {
        "team": "Cape Verde",
        "opponent": "Uruguay",
        "xg": 0.6
      },
      {
        "team": "Egypt",
        "opponent": "New Zealand",
        "xg": 1.16
      },
      {
        "team": "Iran",
        "opponent": "Belgium",
        "xg": 1.03
      },
      {
        "team": "New Zealand",
        "opponent": "Egypt",
        "xg": 0.76
      },
      {
        "team": "Saudi Arabia",
        "opponent": "Spain",
        "xg": 0.54
      },
      {
        "team": "Spain",
        "opponent": "Saudi Arabia",
        "xg": 2.05
      },
      {
        "team": "Uruguay",
        "opponent": "Cape Verde",
        "xg": 1.51
      },
      {
        "team": "Algeria",
        "opponent": "Jordan",
        "xg": 1.33
      },
      {
        "team": "Argentina",
        "opponent": "Austria",
        "xg": 1.63
      },
      {
        "team": "Austria",
        "opponent": "Argentina",
        "xg": 0.82
      },
      {
        "team": "France",
        "opponent": "Iraq",
        "xg": 1.86
      },
      {
        "team": "Iraq",
        "opponent": "France",
        "xg": 0.57
      },
      {
        "team": "Jordan",
        "opponent": "Algeria",
        "xg": 0.72
      },
      {
        "team": "Norway",
        "opponent": "Senegal",
        "xg": 1.06
      },
      {
        "team": "Senegal",
        "opponent": "Norway",
        "xg": 0.95
      },
      {
        "team": "Colombia",
        "opponent": "DR Congo",
        "xg": 1.42
      },
      {
        "team": "Croatia",
        "opponent": "Panama",
        "xg": 1.37
      },
      {
        "team": "DR Congo",
        "opponent": "Colombia",
        "xg": 0.65
      },
      {
        "team": "England",
        "opponent": "Ghana",
        "xg": 2.08
      },
      {
        "team": "Ghana",
        "opponent": "England",
        "xg": 0.46
      },
      {
        "team": "Panama",
        "opponent": "Croatia",
        "xg": 1.18
      },
      {
        "team": "Portugal",
        "opponent": "Uzbekistan",
        "xg": 1.44
      },
      {
        "team": "Uzbekistan",
        "opponent": "Portugal",
        "xg": 0.75
      }
    ],
    "J3": [
      {
        "team": "Bosnia and Herzegovina",
        "opponent": "Qatar",
        "xg": 1.37
      },
      {
        "team": "Brazil",
        "opponent": "Scotland",
        "xg": 1.63
      },
      {
        "team": "Canada",
        "opponent": "Switzerland",
        "xg": 1.26
      },
      {
        "team": "Czech Republic",
        "opponent": "Mexico",
        "xg": 0.74
      },
      {
        "team": "Haiti",
        "opponent": "Morocco",
        "xg": 0.52
      },
      {
        "team": "Mexico",
        "opponent": "Czech Republic",
        "xg": 1.84
      },
      {
        "team": "Morocco",
        "opponent": "Haiti",
        "xg": 1.57
      },
      {
        "team": "Qatar",
        "opponent": "Bosnia and Herzegovina",
        "xg": 0.84
      },
      {
        "team": "Scotland",
        "opponent": "Brazil",
        "xg": 0.77
      },
      {
        "team": "South Africa",
        "opponent": "South Korea",
        "xg": 0.66
      },
      {
        "team": "South Korea",
        "opponent": "South Africa",
        "xg": 1.48
      },
      {
        "team": "Switzerland",
        "opponent": "Canada",
        "xg": 1.11
      },
      {
        "team": "Australia",
        "opponent": "Paraguay",
        "xg": 0.86
      },
      {
        "team": "Curaçao",
        "opponent": "Ivory Coast",
        "xg": 0.47
      },
      {
        "team": "Ecuador",
        "opponent": "Germany",
        "xg": 1.1
      },
      {
        "team": "Germany",
        "opponent": "Ecuador",
        "xg": 0.91
      },
      {
        "team": "Ivory Coast",
        "opponent": "Curaçao",
        "xg": 1.82
      },
      {
        "team": "Japan",
        "opponent": "Sweden",
        "xg": 1.44
      },
      {
        "team": "Netherlands",
        "opponent": "Tunisia",
        "xg": 1.83
      },
      {
        "team": "Paraguay",
        "opponent": "Australia",
        "xg": 1.29
      },
      {
        "team": "Sweden",
        "opponent": "Japan",
        "xg": 0.77
      },
      {
        "team": "Tunisia",
        "opponent": "Netherlands",
        "xg": 0.68
      },
      {
        "team": "Turkey",
        "opponent": "United States",
        "xg": 1.64
      },
      {
        "team": "United States",
        "opponent": "Turkey",
        "xg": 1.26
      },
      {
        "team": "Belgium",
        "opponent": "New Zealand",
        "xg": 1.85
      },
      {
        "team": "Cape Verde",
        "opponent": "Saudi Arabia",
        "xg": 1.06
      },
      {
        "team": "Egypt",
        "opponent": "Iran",
        "xg": 0.79
      },
      {
        "team": "France",
        "opponent": "Norway",
        "xg": 1.4
      },
      {
        "team": "Iran",
        "opponent": "Egypt",
        "xg": 1.0
      },
      {
        "team": "Iraq",
        "opponent": "Senegal",
        "xg": 0.62
      },
      {
        "team": "New Zealand",
        "opponent": "Belgium",
        "xg": 0.82
      },
      {
        "team": "Norway",
        "opponent": "France",
        "xg": 0.98
      },
      {
        "team": "Saudi Arabia",
        "opponent": "Cape Verde",
        "xg": 0.98
      },
      {
        "team": "Senegal",
        "opponent": "Iraq",
        "xg": 1.31
      },
      {
        "team": "Spain",
        "opponent": "Uruguay",
        "xg": 1.26
      },
      {
        "team": "Uruguay",
        "opponent": "Spain",
        "xg": 0.9
      },
      {
        "team": "Algeria",
        "opponent": "Austria",
        "xg": 0.97
      },
      {
        "team": "Argentina",
        "opponent": "Jordan",
        "xg": 2.0
      },
      {
        "team": "Austria",
        "opponent": "Algeria",
        "xg": 1.03
      },
      {
        "team": "Colombia",
        "opponent": "Portugal",
        "xg": 1.38
      },
      {
        "team": "Croatia",
        "opponent": "Ghana",
        "xg": 1.92
      },
      {
        "team": "DR Congo",
        "opponent": "Uzbekistan",
        "xg": 0.77
      },
      {
        "team": "England",
        "opponent": "Panama",
        "xg": 1.43
      },
      {
        "team": "Ghana",
        "opponent": "Croatia",
        "xg": 0.7
      },
      {
        "team": "Jordan",
        "opponent": "Argentina",
        "xg": 0.59
      },
      {
        "team": "Panama",
        "opponent": "England",
        "xg": 0.75
      },
      {
        "team": "Portugal",
        "opponent": "Colombia",
        "xg": 1.27
      },
      {
        "team": "Uzbekistan",
        "opponent": "DR Congo",
        "xg": 0.92
      }
    ]
  }
};
