"""
Converts prediction CSVs and XG CSVs into TypeScript modules in web/src/data/.
Run from the repo root: python3 scripts/export_data.py
"""
import csv
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(ROOT, "web", "src", "data")

VARIANTS = ["misterclaude", "gemaldini", "dav_gpo"]

# ─── helpers ────────────────────────────────────────────────────────────────

def read_csv(path):
    with open(path, encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))

def write_ts(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  wrote {os.path.relpath(path, ROOT)}")

# ─── predictions.ts ─────────────────────────────────────────────────────────

def build_predictions():
    """
    Parse the 3 results CSVs.
    104 data rows per file, structured as:
      rows  0-71 : group stage (12 groups × 6 matches)
      rows 72-87 : R32 (16)
      rows 88-95 : Sweet 16 (8)
      rows 96-99 : Elite 8 (4)
      rows 100-101: Semis (2)
      row  102   : 3rd place
      row  103   : Final
    """
    ROUNDS = [
        ("grupos",     0,  72),
        ("r32",       72,  88),
        ("sweet16",   88,  96),
        ("elite8",    96, 100),
        ("semis",    100, 102),
        ("third",    102, 103),
        ("final",    103, 104),
    ]

    data = {}
    for v in VARIANTS:
        path = os.path.join(ROOT, "results", f"predictions_{v}.csv")
        rows = read_csv(path)
        assert len(rows) == 104, f"{v}: expected 104 rows, got {len(rows)}"

        by_round = {}
        for (name, start, end) in ROUNDS:
            by_round[name] = [
                {
                    "team1":   r["Team_1"],
                    "score1":  int(r["Score_1"]),
                    "score2":  int(r["Score_2"]),
                    "team2":   r["Team_2"],
                }
                for r in rows[start:end]
            ]
        data[v] = by_round

    ts = "// AUTO-GENERATED by scripts/export_data.py — do not edit manually\n\n"
    ts += "export type Variant = 'misterclaude' | 'gemaldini' | 'dav_gpo';\n\n"
    ts += "export interface MatchResult {\n"
    ts += "  team1: string; score1: number; score2: number; team2: string;\n"
    ts += "}\n\n"
    ts += "export interface TournamentRounds {\n"
    ts += "  grupos: MatchResult[]; r32: MatchResult[]; sweet16: MatchResult[];\n"
    ts += "  elite8: MatchResult[]; semis: MatchResult[]; third: MatchResult[]; final: MatchResult[];\n"
    ts += "}\n\n"
    ts += "export const predictions: Record<Variant, TournamentRounds> = "
    ts += json.dumps(data, ensure_ascii=False, indent=2) + ";\n"

    write_ts(os.path.join(OUT, "predictions.ts"), ts)

# ─── xg.ts ──────────────────────────────────────────────────────────────────

def build_xg():
    """Parse XG CSV files for group stage (J1/J2/J3) per variant."""
    data = {}
    for v in VARIANTS:
        jornadas = {}
        for j in ["J1", "J2", "J3"]:
            path = os.path.join(ROOT, "data", "ai_models", f"xg_preds_{j}_{v}.csv")
            rows = read_csv(path)
            jornadas[j] = [
                {
                    "team":     r["team"],
                    "opponent": r["opponent"],
                    "xg":       float(r["xg_estimated"]),
                }
                for r in rows
            ]
        data[v] = jornadas

    ts = "// AUTO-GENERATED by scripts/export_data.py — do not edit manually\n\n"
    ts += "import type { Variant } from './predictions';\n\n"
    ts += "export interface XGEntry { team: string; opponent: string; xg: number; }\n\n"
    ts += "export const xgData: Record<Variant, { J1: XGEntry[]; J2: XGEntry[]; J3: XGEntry[] }> = "
    ts += json.dumps(data, ensure_ascii=False, indent=2) + ";\n"

    write_ts(os.path.join(OUT, "xg.ts"), ts)

# ─── teamStats.ts ─────────────────────────────────────────────────────────

def build_team_stats():
    """
    Extract per-team stats snapshot from the J1_complete files.
    Used by the browser simulator for ELO + rolling averages.
    """
    data = {}
    for v in VARIANTS:
        path = os.path.join(ROOT, "data", "ai_models", f"xg_preds_J1_{v}_complete.csv")
        rows = read_csv(path)
        seen = set()
        teams = {}
        for r in rows:
            name = r["team"]
            if name in seen:
                continue
            seen.add(name)
            try:
                teams[name] = {
                    "elo":       float(r["elo"]),
                    "gfProm5":   float(r["gf_prom_5"]),
                    "gcProm5":   float(r["gc_prom_5"]),
                    "gfProm15":  float(r["gf_prom_15"]),
                    "gcProm15":  float(r["gc_prom_15"]),
                    "pca1":      float(r["PCA_1"]),
                    "pca2":      float(r["PCA_2"]),
                }
            except (KeyError, ValueError):
                pass
        data[v] = teams

    ts = "// AUTO-GENERATED by scripts/export_data.py — do not edit manually\n\n"
    ts += "import type { Variant } from './predictions';\n\n"
    ts += "export interface TeamStats {\n"
    ts += "  elo: number; gfProm5: number; gcProm5: number;\n"
    ts += "  gfProm15: number; gcProm15: number; pca1: number; pca2: number;\n"
    ts += "}\n\n"
    ts += "export const teamStats: Record<Variant, Record<string, TeamStats>> = "
    ts += json.dumps(data, ensure_ascii=False, indent=2) + ";\n"

    write_ts(os.path.join(OUT, "teamStats.ts"), ts)

# ─── mejoresTerceros.ts ─────────────────────────────────────────────────────

def build_mejores_terceros():
    path = os.path.join(ROOT, "data", "mejores_terceros.csv")
    with open(path, encoding="utf-8-sig") as f:
        reader = csv.DictReader(f, delimiter=";")
        rows = list(reader)

    entries = {}
    for r in rows:
        combo = r["Combinación"]
        entries[combo] = {
            "1A": r["1A"], "1B": r["1B"], "1D": r["1D"], "1E": r["1E"],
            "1G": r["1G"], "1I": r["1I"], "1K": r["1K"], "1L": r["1L"],
        }

    ts = "// AUTO-GENERATED by scripts/export_data.py — do not edit manually\n\n"
    ts += "export const mejoresTerceros: Record<string, Record<string, string>> = "
    ts += json.dumps(entries, ensure_ascii=False, indent=2) + ";\n"

    write_ts(os.path.join(OUT, "mejoresTerceros.ts"), ts)

# ─── knockoutXg.ts ───────────────────────────────────────────────────────────

def build_knockout_xg():
    """
    Pre-computes XG for every possible knockout matchup (48×47 ordered pairs)
    using the real XGBoost model. Stored as a static lookup table so the browser
    simulator never needs a network call.
    """
    import numpy as np
    import xgboost as xgb

    FEATURES = [
        'elo', 'opponent_elo', 'is_home', 'tournament_num', 'confed', 'rival_confed',
        'gf_prom_5', 'gc_prom_5', 'elo_prom_5', 'gf_prom_15', 'gc_prom_15', 'PCA_1', 'PCA_2',
        'rival_gf_prom_5', 'rival_gc_prom_5', 'rival_elo_prom_5', 'rival_gf_prom_15',
        'rival_gc_prom_15', 'rival_PCA_1', 'rival_PCA_2',
    ]

    data = {}
    for v in VARIANTS:
        model_path = os.path.join(ROOT, "api", "models", f"xgb_{v}.json")
        model = xgb.XGBRegressor()
        model.load_model(model_path)

        rows = read_csv(os.path.join(ROOT, "data", "ai_models", f"xg_preds_J1_{v}_complete.csv"))
        # foto fija: último registro por equipo (CSV ordenado por fecha)
        teams = {}
        for r in rows:
            teams[r["team"]] = r

        team_names = sorted(teams.keys())
        # Build all ordered pairs in one batch for efficiency
        feat_rows = []
        pair_index = []
        for t1 in team_names:
            for t2 in team_names:
                if t1 == t2:
                    continue
                s1, s2 = teams[t1], teams[t2]
                feat_rows.append([
                    float(s1["elo"]), float(s2["elo"]), 0, 5,
                    int(s1["confed"]), int(s2["confed"]),
                    float(s1["gf_prom_5"]), float(s1["gc_prom_5"]), float(s1["elo_prom_5"]),
                    float(s1["gf_prom_15"]), float(s1["gc_prom_15"]),
                    float(s1["PCA_1"]), float(s1["PCA_2"]),
                    float(s2["gf_prom_5"]), float(s2["gc_prom_5"]), float(s2["elo_prom_5"]),
                    float(s2["gf_prom_15"]), float(s2["gc_prom_15"]),
                    float(s2["PCA_1"]), float(s2["PCA_2"]),
                ])
                pair_index.append((t1, t2))

        preds = model.predict(np.array(feat_rows, dtype=np.float32))

        # Build nested dict: xg[team1][team2] = xg of team1 when facing team2
        nested = {}
        for (t1, t2), xg in zip(pair_index, preds):
            if t1 not in nested:
                nested[t1] = {}
            nested[t1][t2] = round(float(xg), 3)

        data[v] = nested
        print(f"  [{v}] {len(pair_index)} pares calculados")

    ts = "// AUTO-GENERATED by scripts/export_data.py — do not edit manually\n\n"
    ts += "import type { Variant } from './predictions';\n\n"
    ts += "// knockoutXg[variant][team1][team2] = XG esperado de team1 enfrentando a team2 en eliminatorias\n"
    ts += "export const knockoutXg: Record<Variant, Record<string, Record<string, number>>> = "
    ts += json.dumps(data, ensure_ascii=False) + ";\n"

    write_ts(os.path.join(OUT, "knockoutXg.ts"), ts)

# ─── metadata.ts ─────────────────────────────────────────────────────────────

TRAINING_CUTOFF = "2026-06-11"

def build_metadata():
    from datetime import date
    meta = {
        "trainingCutoff": TRAINING_CUTOFF,
        "generatedAt": date.today().isoformat(),
    }
    ts = "// AUTO-GENERATED by scripts/export_data.py — do not edit manually\n\n"
    ts += f"export const metadata = {json.dumps(meta)} as const;\n"
    write_ts(os.path.join(OUT, "metadata.ts"), ts)

# ─── realResults.ts ──────────────────────────────────────────────────────────

def build_real_results():
    """
    Converts data/world_cup_results.csv (fetched from football-data.org)
    into web/src/data/realResults.ts for display in the Grupos tab.
    If the source file doesn't exist, writes an empty array so the build
    always succeeds.
    """
    path = os.path.join(ROOT, "data", "world_cup_results.csv")

    ts = "// AUTO-GENERATED by scripts/export_data.py — do not edit manually\n\n"
    ts += "export interface RealResult {\n"
    ts += "  date: string; homeTeam: string; awayTeam: string;\n"
    ts += "  homeGoals: number; awayGoals: number;\n}\n\n"

    if not os.path.exists(path):
        ts += "export const realResults: RealResult[] = [];\n"
        write_ts(os.path.join(OUT, "realResults.ts"), ts)
        return

    rows = read_csv(path)
    entries = [
        {
            "date":      r["date"],
            "homeTeam":  r["home_team"],
            "awayTeam":  r["away_team"],
            "homeGoals": int(r["home_goals"]),
            "awayGoals": int(r["away_goals"]),
        }
        for r in rows
    ]

    ts += "export const realResults: RealResult[] = "
    ts += json.dumps(entries, ensure_ascii=False, indent=2) + ";\n"
    write_ts(os.path.join(OUT, "realResults.ts"), ts)



# ─── main ────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("Exportando datos a TypeScript...")
    build_real_results()
    build_predictions()
    build_xg()
    build_team_stats()
    build_mejores_terceros()
    build_metadata()
    print("Calculando XG de eliminatorias para todas las combinaciones...")
    build_knockout_xg()
    print("✅ Listo.")
